# Generated by Django 5.1 on 2025-10-03 07:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout', models.CharField(choices=[('grid', 'Grid Layout'), ('masonry', 'Masonry Layout'), ('flex', 'Flexible Layout'), ('custom', 'Custom Layout')], default='grid', max_length=20)),
                ('columns', models.IntegerField(default=12, help_text='Number of columns in grid layout', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('is_public', models.BooleanField(default=False, help_text='Allow all users to view this dashboard')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default dashboard for users')),
                ('auto_refresh', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=300, help_text='Auto-refresh interval in seconds')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('view', 'Dashboard Viewed'), ('widget_added', 'Widget Added'), ('widget_removed', 'Widget Removed'), ('widget_updated', 'Widget Updated'), ('layout_changed', 'Layout Changed'), ('shared', 'Dashboard Shared'), ('exported', 'Dashboard Exported')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.dashboard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Activity',
                'verbose_name_plural': 'Dashboard Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('snapshot_data', models.JSONField(default=dict, help_text='Complete dashboard configuration and data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_snapshots', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.dashboard')),
            ],
            options={
                'verbose_name': 'Dashboard Snapshot',
                'verbose_name_plural': 'Dashboard Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('metric_name', models.CharField(max_length=255)),
                ('value', models.JSONField(help_text='Cached metric value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Metric Cache',
                'verbose_name_plural': 'Metric Caches',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['metric_key'], name='dashboard_m_metric__700620_idx'), models.Index(fields=['expires_at'], name='dashboard_m_expires_24cd91_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(help_text='Type of action (link, modal, api_call, etc.)', max_length=50)),
                ('action_url', models.CharField(blank=True, help_text='URL or endpoint for the action', max_length=500)),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='Additional action configuration')),
                ('icon', models.CharField(choices=[('plus', 'Plus'), ('edit', 'Edit'), ('trash', 'Trash'), ('eye', 'View'), ('download', 'Download'), ('upload', 'Upload'), ('refresh', 'Refresh'), ('settings', 'Settings'), ('user', 'User'), ('file', 'File'), ('search', 'Search')], default='plus', max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_quick_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Action',
                'verbose_name_plural': 'Quick Actions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('compact_mode', models.BooleanField(default=False)),
                ('show_grid_lines', models.BooleanField(default=True)),
                ('default_refresh_interval', models.IntegerField(default=300)),
                ('enable_animations', models.BooleanField(default=True)),
                ('show_notifications', models.BooleanField(default=True)),
                ('show_quick_actions', models.BooleanField(default=True)),
                ('show_activity_feed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='dashboard.dashboard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dashboard Preference',
                'verbose_name_plural': 'User Dashboard Preferences',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('widget_type', models.CharField(choices=[('metric', 'Metric Card'), ('chart', 'Chart'), ('table', 'Data Table'), ('list', 'List'), ('calendar', 'Calendar'), ('activity', 'Activity Feed'), ('quick_actions', 'Quick Actions'), ('notification', 'Notifications'), ('gauge', 'Gauge'), ('progress', 'Progress Bar'), ('map', 'Map'), ('custom', 'Custom Widget')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot'), ('radar', 'Radar Chart')], max_length=20)),
                ('data_source', models.CharField(help_text='Model or data source name', max_length=100)),
                ('query_config', models.JSONField(blank=True, default=dict, help_text='Query configuration and filters')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('height', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(100)])),
                ('size', models.CharField(choices=[('small', 'Small (3 cols)'), ('medium', 'Medium (6 cols)'), ('large', 'Large (9 cols)'), ('full', 'Full Width (12 cols)')], default='medium', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('show_title', models.BooleanField(default=True)),
                ('show_border', models.BooleanField(default=True)),
                ('title_color', models.CharField(default='#333333', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('auto_refresh', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=300, help_text='Refresh interval in seconds')),
                ('custom_css', models.TextField(blank=True)),
                ('custom_config', models.JSONField(blank=True, default=dict, help_text='Additional widget-specific configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.dashboard')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['dashboard', 'order', 'position_y', 'position_x'],
            },
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['created_by', 'is_active'], name='dashboard_d_created_291d36_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_public', 'is_active'], name='dashboard_d_is_publ_e9fa3f_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_default'], name='dashboard_d_is_defa_847543_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardactivity',
            index=models.Index(fields=['dashboard', '-created_at'], name='dashboard_d_dashboa_dd7c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardactivity',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_d_user_id_b651a6_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='dashboard_d_activit_722346_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsnapshot',
            index=models.Index(fields=['dashboard', '-created_at'], name='dashboard_d_dashboa_d54f75_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['dashboard', 'is_active'], name='dashboard_w_dashboa_4f2091_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['widget_type'], name='dashboard_w_widget__9b0ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['order'], name='dashboard_w_order_3dcade_idx'),
        ),
    ]
