# Generated by Django 5.1 on 2025-10-03 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales Person'), ('accountant', 'Accountant'), ('auctioneer', 'Auctioneer'), ('manager', 'Manager'), ('clerk', 'Clerk')], help_text='User role (admin, sales, etc.)', max_length=20, verbose_name='User Role')),
                ('module_name', models.CharField(choices=[('dashboard', 'Dashboard'), ('vehicles', 'Vehicle Management'), ('clients', 'Client Management'), ('payments', 'Payment Management'), ('payroll', 'Payroll Management'), ('expenses', 'Expense Tracking'), ('repossessions', 'Repossessions'), ('auctions', 'Auction Management'), ('insurance', 'Insurance Management'), ('notifications', 'Notifications'), ('documents', 'Document Management'), ('reports', 'Reports'), ('audit', 'Audit Logs'), ('permissions', 'Permissions Management')], help_text='System module', max_length=50, verbose_name='Module Name')),
                ('access_level', models.CharField(choices=[('no_access', 'No Access'), ('read_only', 'Read Only'), ('read_write', 'Read & Write'), ('full_access', 'Full Access')], default='no_access', help_text='Level of access to this module', max_length=20, verbose_name='Access Level')),
                ('can_create', models.BooleanField(default=False, help_text='Can create new records', verbose_name='Can Create')),
                ('can_edit', models.BooleanField(default=False, help_text='Can edit existing records', verbose_name='Can Edit')),
                ('can_delete', models.BooleanField(default=False, help_text='Can delete records', verbose_name='Can Delete')),
                ('can_export', models.BooleanField(default=False, help_text='Can export data to PDF/Excel', verbose_name='Can Export')),
                ('description', models.TextField(blank=True, help_text='Optional description of this permission', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
                'ordering': ['role', 'module_name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=20, verbose_name='Action')),
                ('old_value', models.JSONField(blank=True, help_text='Previous permission settings', null=True, verbose_name='Old Value')),
                ('new_value', models.JSONField(blank=True, help_text='New permission settings', null=True, verbose_name='New Value')),
                ('reason', models.TextField(blank=True, help_text='Reason for change', verbose_name='Reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='permissions.rolepermission')),
            ],
            options={
                'verbose_name': 'Permission History',
                'verbose_name_plural': 'Permission History',
                'db_table': 'permission_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'module_name'], name='role_permis_role_4d519f_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['is_active'], name='role_permis_is_acti_791066_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'module_name')},
        ),
    ]
