# Generated by Django 5.1 on 2025-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales Person'), ('accountant', 'Accountant'), ('auctioneer', 'Auctioneer'), ('manager', 'Manager'), ('clerk', 'Clerk'), ('client', 'Client')], help_text='User role (admin, sales, etc.)', max_length=20, verbose_name='User Role'),
        ),
    ]
