# Generated by Django 5.1 on 2026-07-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_rolepermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module_name',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('vehicles', 'Vehicle Management'), ('clients', 'Client Management'), ('payments', 'Payment Management'), ('payroll', 'Payroll Management'), ('expenses', 'Expense Tracking'), ('repossessions', 'Repossessions'), ('auctions', 'Auction Management'), ('insurance', 'Insurance Management'), ('notifications', 'Notifications'), ('documents', 'Document Management'), ('reports', 'Reports'), ('audit', 'Audit Logs'), ('permissions', 'Permissions Management'), ('finance', 'Finance & Accounts')], help_text='System module', max_length=50, verbose_name='Module Name'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales Person'), ('accountant', 'Accountant'), ('auctioneer', 'Auctioneer'), ('manager', 'Manager'), ('clerk', 'Clerk'), ('client', 'Client'), ('auditor', 'Auditor')], help_text='User role (admin, sales, etc.)', max_length=20, verbose_name='User Role'),
        ),
    ]
