# Generated by Django 5.1 on 2025-10-03 07:16

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auction_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('auction_type', models.CharField(choices=[('standard', 'Standard Auction'), ('reserve', 'Reserve Auction'), ('no_reserve', 'No Reserve Auction'), ('silent', 'Silent Auction'), ('live', 'Live Auction')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price seller will accept (hidden from bidders)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_bid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum amount each bid must increase', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional instant purchase price', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('extended_end_date', models.DateTimeField(blank=True, null=True)),
                ('allow_proxy_bidding', models.BooleanField(default=True)),
                ('auto_extend', models.BooleanField(default=True, help_text='Automatically extend auction if bid placed in last 5 minutes')),
                ('extension_minutes', models.IntegerField(default=5, help_text='Minutes to extend if late bid received', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('minimum_bidders', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('require_registration', models.BooleanField(default=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('require_deposit', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('winning_bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reserve_met', models.BooleanField(default=False)),
                ('total_bids', models.IntegerField(default=0)),
                ('unique_bidders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('inspection_available', models.BooleanField(default=True)),
                ('inspection_location', models.CharField(blank=True, max_length=255)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured auctions')),
                ('views_count', models.IntegerField(default=0)),
                ('watchers_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AuctionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('registration_fee_paid', models.BooleanField(default=False)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_refunded', models.BooleanField(default=False)),
                ('total_bids', models.IntegerField(default=0)),
                ('highest_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proxy_bid_enabled', models.BooleanField(default=False)),
                ('proxy_max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Auction Participant',
                'verbose_name_plural': 'Auction Participants',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('partial', 'Partial Payment'), ('paid', 'Fully Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_due_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_completed_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('buyers_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional fee charged to buyer', max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Auction Result',
                'verbose_name_plural': 'Auction Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionWatchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notify_before_end', models.BooleanField(default=True)),
                ('notify_on_outbid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Auction Watchlist',
                'verbose_name_plural': 'Auction Watchlists',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bid_type', models.CharField(choices=[('manual', 'Manual Bid'), ('proxy', 'Proxy Bid'), ('auto', 'Automatic Bid')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_winning_bid', models.BooleanField(default=False)),
                ('is_outbid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['-bid_amount', 'created_at'],
            },
        ),
    ]
