# Generated by Django 5.1 on 2025-10-03 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionparticipant',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionparticipant',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionparticipant',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_participations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='auctionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionresult',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionresult',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_wins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionwatchlist',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionwatchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionresult',
            name='winning_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_results', to='auctions.bid'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'start_date'], name='auctions_au_status_a5edbf_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['end_date'], name='auctions_au_end_dat_6d3244_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['auction_number'], name='auctions_au_auction_81e140_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['vehicle'], name='auctions_au_vehicle_afcd95_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionparticipant',
            index=models.Index(fields=['auction', 'user'], name='auctions_au_auction_a80d30_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionparticipant',
            index=models.Index(fields=['is_approved'], name='auctions_au_is_appr_9fe1f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auctionparticipant',
            unique_together={('auction', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='auctionwatchlist',
            unique_together={('auction', 'user')},
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-bid_amount', 'created_at'], name='auctions_bi_auction_353349_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', '-created_at'], name='auctions_bi_bidder__c14e80_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['is_winning_bid'], name='auctions_bi_is_winn_bafcfe_idx'),
        ),
    ]
