# Generated by Django 5.1 on 2025-10-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.EmailField(help_text='Email address used in login attempt', max_length=254, verbose_name='Email Attempted')),
                ('success', models.BooleanField(default=False, help_text='Whether login was successful', verbose_name='Success')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failed login', max_length=255, null=True, verbose_name='Failure Reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('location', models.CharField(blank=True, help_text='Approximate location based on IP', max_length=255, null=True, verbose_name='Location')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Session Key')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Login Time')),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
                'db_table': 'login_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export')], db_index=True, help_text='Type of action performed', max_length=20, verbose_name='Action Type')),
                ('description', models.TextField(help_text='Human-readable description of the action', verbose_name='Description')),
                ('object_id', models.CharField(blank=True, db_index=True, help_text='ID of the object that was affected', max_length=255, null=True, verbose_name='Object ID')),
                ('model_name', models.CharField(blank=True, db_index=True, help_text='Name of the model that was affected', max_length=100, null=True, verbose_name='Model Name')),
                ('changes', models.JSONField(blank=True, help_text='JSON object containing old and new values', null=True, verbose_name='Changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', null=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, help_text='URL path that was accessed', max_length=500, null=True, verbose_name='Request Path')),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE)', max_length=10, null=True, verbose_name='Request Method')),
                ('additional_data', models.JSONField(blank=True, help_text='Any additional contextual data', null=True, verbose_name='Additional Data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred', verbose_name='Timestamp')),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of object that was affected', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
