# Generated by Django 5.1 on 2025-10-03 07:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total purchase amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial deposit paid', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monthly_installment', models.DecimalField(decimal_places=2, help_text='Monthly installment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('number_of_installments', models.PositiveIntegerField(help_text='Number of monthly installments', validators=[django.core.validators.MinValueValidator(1)])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual interest rate (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField(help_text='Date when payment plan starts')),
                ('end_date', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is active')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether all payments have been made')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the plan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_vehicle', models.OneToOneField(help_text='Vehicle purchase this plan is for', on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='clients.clientvehicle')),
                ('created_by', models.ForeignKey(help_text='User who created this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Installment Plan',
                'verbose_name_plural': 'Installment Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date payment was received')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('other', 'Other')], default='cash', help_text='Method of payment', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction reference number (M-Pesa code, cheque number, etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment', null=True)),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt number for this payment', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_vehicle', models.ForeignKey(help_text='Vehicle purchase this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.clientvehicle')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(help_text='Installment number (1, 2, 3, etc.)')),
                ('due_date', models.DateField(help_text='Date this installment is due')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Amount due for this installment', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid for this installment', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this installment has been paid')),
                ('payment_date', models.DateField(blank=True, help_text='Date payment was received', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_plan', models.ForeignKey(help_text='Installment plan this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='payments.installmentplan')),
                ('payment', models.ForeignKey(blank=True, help_text='Payment that fulfilled this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_schedules', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Schedule',
                'verbose_name_plural': 'Payment Schedules',
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('call', 'Phone Call'), ('letter', 'Physical Letter')], default='sms', help_text='Type of reminder', max_length=20)),
                ('reminder_date', models.DateTimeField(auto_now_add=True, help_text='Date reminder was sent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('responded', 'Client Responded')], default='pending', help_text='Status of the reminder', max_length=20)),
                ('message', models.TextField(help_text='Reminder message content')),
                ('client_response', models.TextField(blank=True, help_text="Client's response to the reminder", null=True)),
                ('response_date', models.DateTimeField(blank=True, help_text='Date client responded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(help_text='User who sent this reminder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
                ('payment_schedule', models.ForeignKey(help_text='Payment schedule this reminder is for', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='payments.paymentschedule')),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
                'ordering': ['-reminder_date'],
            },
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['start_date', 'end_date'], name='payments_in_start_d_a4da7f_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['is_active', 'is_completed'], name='payments_in_is_acti_3e51bb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_pa_payment_5c92d7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client_vehicle', 'payment_date'], name='payments_pa_client__fb1fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['due_date'], name='payments_pa_due_dat_2df77e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['is_paid'], name='payments_pa_is_paid_07ebb6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['installment_plan', 'due_date'], name='payments_pa_install_4687d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentschedule',
            unique_together={('installment_plan', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='paymentreminder',
            index=models.Index(fields=['reminder_date'], name='payments_pa_reminde_51b9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreminder',
            index=models.Index(fields=['status'], name='payments_pa_status_bc3c8d_idx'),
        ),
    ]
