# Generated by Django 5.1 on 2026-05-06 22:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='monthly_installment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly installment amount (auto-calculated if blank)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
