# Generated by Django 5.0.7 on 2026-05-09 13:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='late_fee_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fees applied (0.1% per day, max 50% of amount due)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
