# Generated by Django 5.1 on 2026-05-11 04:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_installmentplan_interest_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaybillBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('request_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('conversation_id', models.CharField(blank=True, default='', max_length=120)),
                ('originator_conversation_id', models.CharField(blank=True, default='', max_length=120)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paybill Balance Snapshot',
                'verbose_name_plural': 'Paybill Balance Snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_523e30_idx'), models.Index(fields=['created_at'], name='payments_pa_created_56280b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaybillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('trans_time', models.DateTimeField(blank=True, null=True)),
                ('trans_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('business_short_code', models.CharField(blank=True, default='', max_length=20)),
                ('bill_ref_number', models.CharField(blank=True, default='', max_length=120)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=120)),
                ('org_account_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Organization account balance as shared in C2B callback, if available.', max_digits=14, null=True)),
                ('msisdn', models.CharField(blank=True, default='', max_length=20)),
                ('first_name', models.CharField(blank=True, default='', max_length=80)),
                ('middle_name', models.CharField(blank=True, default='', max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('is_linked_to_payment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paybill Transaction',
                'verbose_name_plural': 'Paybill Transactions',
                'ordering': ['-trans_time', '-created_at'],
                'indexes': [models.Index(fields=['msisdn'], name='payments_pa_msisdn_08a430_idx'), models.Index(fields=['bill_ref_number'], name='payments_pa_bill_re_16c30d_idx'), models.Index(fields=['created_at'], name='payments_pa_created_0304ea_idx')],
            },
        ),
    ]
