# Generated by Django 5.1 on 2026-05-19 02:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_vehicletracker_certificate_number'),
        ('payments', '0007_paybillbalancesnapshot_paybilltransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaSTKRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_reference', models.CharField(blank=True, default='', max_length=120)),
                ('payment_type', models.CharField(blank=True, default='', max_length=40)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('response_code', models.CharField(blank=True, default='', max_length=20)),
                ('response_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True, default='')),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('raw_request_payload', models.JSONField(blank=True, default=dict)),
                ('raw_response_payload', models.JSONField(blank=True, default=dict)),
                ('raw_callback_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_stk_requests', to='clients.clientvehicle')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_stk_request', to='payments.payment')),
            ],
            options={
                'verbose_name': 'M-Pesa STK Request',
                'verbose_name_plural': 'M-Pesa STK Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_mp_status_0363fb_idx'), models.Index(fields=['account_reference'], name='payments_mp_account_731eef_idx'), models.Index(fields=['created_at'], name='payments_mp_created_395ffc_idx')],
            },
        ),
    ]
