# Generated by Django 5.1 on 2026-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_mpesastkrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('mixed', 'Multiple Methods'), ('other', 'Other')], default='cash', help_text='Method of payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsplit',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('mixed', 'Multiple Methods'), ('other', 'Other')], help_text='Payment method for this portion', max_length=20),
        ),
    ]
