# Generated by Django 5.0.7 on 2026-06-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_location',
            field=models.CharField(blank=True, help_text='Where payment was made (branch, office, channel point, etc.)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='payment_location',
            field=models.CharField(blank=True, help_text='Where this split payment portion was made', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('equity_hoza', 'Equity Hoza'), ('dib_hoza', 'DIB Hoza'), ('coop_hoza', 'COOP Hoza'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('mixed', 'Multiple Methods'), ('other', 'Other')], default='cash', help_text='Method of payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsplit',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('equity_hoza', 'Equity Hoza'), ('dib_hoza', 'DIB Hoza'), ('coop_hoza', 'COOP Hoza'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('mixed', 'Multiple Methods'), ('other', 'Other')], help_text='Payment method for this portion', max_length=20),
        ),
    ]
