# Generated by Django 5.0.7 on 2026-06-09 00:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.core.validators import MinValueValidator
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_payment_location_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS public.payments_accountwithdrawal CASCADE; "
                "DROP TYPE IF EXISTS public.payments_accountwithdrawal;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='AccountWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('equity_hoza', 'Equity Hoza'), ('dib_hoza', 'DIB Hoza'), ('coop_hoza', 'COOP Hoza'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE')], help_text='HOZA or KE account where the withdrawal originated', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal('0.01'))], help_text='Withdrawal amount')),
                ('withdrawal_date', models.DateField(default=django.utils.timezone.now, help_text='Date the withdrawal was recorded')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the withdrawal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-withdrawal_date', '-created_at'],
                'verbose_name': 'Account Withdrawal',
                'verbose_name_plural': 'Account Withdrawals',
            },
        ),
        migrations.AddIndex(
            model_name='accountwithdrawal',
            index=models.Index(fields=['withdrawal_date'], name='payments_accoun_withdrw_withdrw_41a38f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountwithdrawal',
            index=models.Index(fields=['payment_method'], name='payments_accoun_withdrw_paymen_4bd8b4_idx'),
        ),
    ]
