# Generated by Django 5.1 on 2026-06-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_accountwithdrawal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountwithdrawal',
            new_name='payments_ac_withdra_346742_idx',
            old_name='payments_accoun_withdrw_withdrw_41a38f_idx',
        ),
        migrations.RenameIndex(
            model_name='accountwithdrawal',
            new_name='payments_ac_payment_f7f3a6_idx',
            old_name='payments_accoun_withdrw_paymen_4bd8b4_idx',
        ),
    ]
