# Generated by Django 5.1 on 2026-06-30 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_rename_payments_accoun_withdrw_withdrw_41a38f_idx_payments_ac_withdra_346742_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_reversed',
            field=models.BooleanField(default=False, help_text='Whether this payment has been reversed/voided'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversal_reason',
            field=models.TextField(blank=True, help_text='Reason this payment was reversed', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='When this payment was reversed', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='User who reversed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
