# Generated by Django 5.1 on 2026-06-30 20:01
# Updated to use IF NOT EXISTS so it is safe to run against a database
# that already has these columns (e.g. from a prior manual script).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_rename_payments_accoun_withdrw_withdrw_41a38f_idx_payments_ac_withdra_346742_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database side: use IF NOT EXISTS so re-running on a DB that already
            # has these columns is a no-op instead of an error.
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE payments_payment ADD COLUMN IF NOT EXISTS is_reversed boolean NOT NULL DEFAULT false",
                    reverse_sql="ALTER TABLE payments_payment DROP COLUMN IF EXISTS is_reversed",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE payments_payment ADD COLUMN IF NOT EXISTS reversal_reason text NULL",
                    reverse_sql="ALTER TABLE payments_payment DROP COLUMN IF EXISTS reversal_reason",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE payments_payment ADD COLUMN IF NOT EXISTS reversed_at timestamptz NULL",
                    reverse_sql="ALTER TABLE payments_payment DROP COLUMN IF EXISTS reversed_at",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE payments_payment ADD COLUMN IF NOT EXISTS reversed_by_id integer NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED",
                    reverse_sql="ALTER TABLE payments_payment DROP COLUMN IF EXISTS reversed_by_id",
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS payments_payment_reversed_by_id_idx ON payments_payment (reversed_by_id)",
                    reverse_sql="DROP INDEX IF EXISTS payments_payment_reversed_by_id_idx",
                ),
            ],
            # State side: tell Django's ORM about the new fields as usual.
            state_operations=[
                migrations.AddField(
                    model_name='payment',
                    name='is_reversed',
                    field=models.BooleanField(default=False, help_text='Whether this payment has been reversed/voided'),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='reversal_reason',
                    field=models.TextField(blank=True, help_text='Reason this payment was reversed', null=True),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='reversed_at',
                    field=models.DateTimeField(blank=True, help_text='When this payment was reversed', null=True),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='reversed_by',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='User who reversed this payment',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reversed_payments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
