# Generated by Django 5.1 on 2026-07-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('payments', '0013_payment_is_reversed_payment_reversal_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Financial account this payment was received into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.financialaccount'),
        ),
    ]
