# Generated by Django 5.1 on 2026-07-03 01:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_alter_client_status'),
        ('payments', '0013_payment_is_reversed_payment_reversal_reason_and_more'),
        ('vehicles', '0019_alter_vehicle_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('hoza', 'Hoza'), ('ke', 'KE'), ('cash', 'Cash'), ('other', 'Other')], help_text='Which breakdown page this account appears on', max_length=10)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('other', 'Other')], default='bank', max_length=20)),
                ('payment_method_code', models.CharField(blank=True, help_text='Matches Payment.PAYMENT_METHOD_CHOICES for legacy Hoza/KE accounts; blank for new accounts', max_length=20, null=True, unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot receive new transactions/transfers but remain in historical ledgers')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='payments.account')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='payments.account')),
            ],
            options={
                'verbose_name': 'Account Transfer',
                'verbose_name_plural': 'Account Transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('money_in', 'Money Received'), ('money_out', 'Money Paid Out'), ('refund', 'Refund'), ('bank_charge', 'Bank Charge'), ('correction', 'Correction'), ('opening_balance_adjustment', 'Opening Balance Adjustment'), ('other_income', 'Other Income'), ('other_expense', 'Other Expense'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=30)),
                ('direction', models.CharField(choices=[('in', 'Money In'), ('out', 'Money Out')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('narration', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='account_transactions/%Y/%m/')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='clients.client')),
                ('related_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='vehicles.vehicle')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions_reversed', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='payments.accounttransfer')),
            ],
            options={
                'verbose_name': 'Account Transaction',
                'verbose_name_plural': 'Account Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['category'], name='payments_ac_categor_b325c1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='payments_ac_is_acti_1d91bd_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['account', 'date'], name='payments_ac_account_674a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['approval_status'], name='payments_ac_approva_29bfb6_idx'),
        ),
    ]
