# Generated by Django 5.1 on 2026-07-03 01:30

from django.db import migrations

LEGACY_ACCOUNTS = [
    ('equity_hoza', 'Equity Hoza', 'hoza'),
    ('dib_hoza', 'DIB Hoza', 'hoza'),
    ('coop_hoza', 'COOP Hoza', 'hoza'),
    ('kcb_ke', 'KCB KE', 'ke'),
    ('absa_ke', 'ABSA KE', 'ke'),
    ('equity_ke', 'Equity KE', 'ke'),
]


def seed_legacy_accounts(apps, schema_editor):
    Account = apps.get_model('payments', 'Account')
    for code, name, category in LEGACY_ACCOUNTS:
        Account.objects.get_or_create(
            payment_method_code=code,
            defaults={
                'name': name,
                'category': category,
                'account_type': 'bank',
                'opening_balance': 0,
                'is_active': True,
            },
        )


def remove_legacy_accounts(apps, schema_editor):
    Account = apps.get_model('payments', 'Account')
    codes = [code for code, _, _ in LEGACY_ACCOUNTS]
    Account.objects.filter(payment_method_code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_account_accounttransfer_accounttransaction_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_legacy_accounts, remove_legacy_accounts),
    ]
