# Generated by Django 5.1 on 2026-07-03 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_alter_client_status'),
        ('payments', '0015_seed_legacy_accounts'),
        ('vehicles', '0019_alter_vehicle_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_suspense',
            field=models.BooleanField(default=False, help_text='Holding account for unclear/unverified payments awaiting allocation'),
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('wrong_account', 'Wrong Account'), ('wrong_client', 'Wrong Client'), ('wrong_vehicle', 'Wrong Vehicle'), ('unmatched', 'Unmatched / Suspense Payment'), ('wrong_reference', 'Wrong Reference'), ('duplicate', 'Duplicate / Mistaken Posting'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_approved', to=settings.AUTH_USER_MODEL)),
                ('correct_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.account')),
                ('correct_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.client')),
                ('correct_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicle')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_initiated', to=settings.AUTH_USER_MODEL)),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='payments.accounttransaction')),
                ('resulting_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.accounttransaction')),
            ],
            options={
                'verbose_name': 'Reconciliation',
                'verbose_name_plural': 'Reconciliations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_re_status_e524c3_idx')],
            },
        ),
    ]
