# Generated by Django 5.1 on 2026-07-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_alter_client_status'),
        ('payments', '0016_account_is_suspense_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='correct_client_vehicle',
            field=models.ForeignKey(blank=True, help_text='Used only for payment-path reconciliations (wrong client/vehicle)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.clientvehicle'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='original_payment',
            field=models.ForeignKey(blank=True, help_text='Set for client-payment reconciliations; mutually exclusive with original_transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='resulting_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='original_transaction',
            field=models.ForeignKey(blank=True, help_text='Set for account-ledger reconciliations; mutually exclusive with original_payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='payments.accounttransaction'),
        ),
    ]
