# Generated by Django 5.1 on 2026-07-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_reconciliation_correct_client_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='direction',
            field=models.CharField(choices=[('in', 'Debit'), ('out', 'Credit')], max_length=3),
        ),
    ]
