# Generated by Django 5.1 on 2026-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_accounttransaction_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybilltransaction',
            name='business_short_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paybilltransaction',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paybilltransaction',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paybilltransaction',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paybilltransaction',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paybilltransaction',
            name='msisdn',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paybilltransaction',
            name='trans_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
