# Generated by Django 5.1 on 2026-07-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_paybilltransaction_business_short_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybilltransaction',
            name='msisdn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
