# Generated by Django 5.1 on 2026-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_paybilltransaction_msisdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesastkrequest',
            name='business_short_code',
            field=models.CharField(blank=True, default='', help_text='Which paybill this STK push was sent from (MPESA_SHORTCODE or _2)', max_length=20),
        ),
        migrations.AddField(
            model_name='paybillbalancesnapshot',
            name='business_short_code',
            field=models.CharField(blank=True, default='', help_text='Which paybill this balance snapshot is for (MPESA_SHORTCODE or _2)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paybillbalancesnapshot',
            index=models.Index(fields=['business_short_code'], name='payments_pa_busines_c81300_idx'),
        ),
    ]
