# Generated by Django 5.1 on 2025-10-03 07:16

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('payment', 'Payment'), ('vehicle', 'Vehicle'), ('client', 'Client'), ('auction', 'Auction'), ('bid', 'Bid'), ('document', 'Document'), ('insurance', 'Insurance'), ('repossession', 'Repossession'), ('expense', 'Expense'), ('payroll', 'Payroll'), ('registration', 'Registration'), ('delivery', 'Delivery'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('note', 'Note')], db_index=True, default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('related_object_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_methods', models.JSONField(blank=True, default=list, help_text='List of delivery methods: in_app, email, sms, push')),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('group_key', models.CharField(blank=True, db_index=True, help_text='Key for grouping related notifications', max_length=100)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_address', models.EmailField(blank=True, help_text='Override default email', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('email_digest', models.BooleanField(default=False, help_text='Receive daily email digest instead of individual emails')),
                ('email_digest_time', models.TimeField(default=datetime.time(9, 0, 0, 528961), help_text='Time to send daily digest')),
                ('sms_enabled', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('push_enabled', models.BooleanField(default=True)),
                ('notify_payment', models.BooleanField(default=True)),
                ('notify_vehicle', models.BooleanField(default=True)),
                ('notify_auction', models.BooleanField(default=True)),
                ('notify_document', models.BooleanField(default=True)),
                ('notify_insurance', models.BooleanField(default=True)),
                ('notify_repossession', models.BooleanField(default=True)),
                ('notify_expense', models.BooleanField(default=True)),
                ('notify_payroll', models.BooleanField(default=True)),
                ('notify_system', models.BooleanField(default=True)),
                ('notify_urgent_only', models.BooleanField(default=False, help_text='Only receive urgent notifications')),
                ('notify_high_and_urgent', models.BooleanField(default=False, help_text='Only receive high and urgent notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default=datetime.time(22, 0, 0, 529972))),
                ('quiet_hours_end', models.TimeField(default=datetime.time(8, 0, 0, 529972))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('push', 'Push')], max_length=20)),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('payment', 'Payment'), ('vehicle', 'Vehicle'), ('client', 'Client'), ('auction', 'Auction'), ('bid', 'Bid'), ('document', 'Document'), ('insurance', 'Insurance'), ('repossession', 'Repossession'), ('expense', 'Expense'), ('payroll', 'Payroll'), ('registration', 'Registration'), ('delivery', 'Delivery'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('note', 'Note')], max_length=20)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('html_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('payment', 'Payment'), ('vehicle', 'Vehicle'), ('client', 'Client'), ('auction', 'Auction'), ('bid', 'Bid'), ('document', 'Document'), ('insurance', 'Insurance'), ('repossession', 'Repossession'), ('expense', 'Expense'), ('payroll', 'Payroll'), ('registration', 'Registration'), ('delivery', 'Delivery'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('note', 'Note')], default='info', max_length=20)),
                ('user_filter', models.JSONField(blank=True, default=dict, help_text='Filter criteria for dynamic user selection')),
                ('frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification Schedule',
                'verbose_name_plural': 'Notification Schedules',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_3fc670_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group_key'], name='notificatio_group_k_49f5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', 'delivery_method'], name='notificatio_notific_257f61_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_361e70_idx'),
        ),
    ]
