# Generated by Django 5.1 on 2026-05-06 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_digest_time',
            field=models.TimeField(default=datetime.time(9, 0, 0, 399158), help_text='Time to send daily digest'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(8, 0, 0, 399158)),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(22, 0, 0, 399158)),
        ),
    ]
