# Generated by Django 5.1 on 2025-10-13 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationpreference_email_digest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_digest_time',
            field=models.TimeField(default=datetime.time(9, 0, 0, 161269), help_text='Time to send daily digest'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(8, 0, 0, 162234)),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(22, 0, 0, 162234)),
        ),
    ]
