# Generated by Django 5.1 on 2026-05-12 06:59

import apps.notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationpreference_email_digest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_digest_time',
            field=models.TimeField(default=apps.notifications.models.default_email_digest_time, help_text='Time to send daily digest'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_end',
            field=models.TimeField(default=apps.notifications.models.default_quiet_hours_end),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_start',
            field=models.TimeField(default=apps.notifications.models.default_quiet_hours_start),
        ),
    ]
