# Generated by Django 5.1 on 2025-10-03 07:16

import django.core.validators
import django.db.models.deletion
import utils.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Vehicle manufacturer (e.g., Toyota, Honda, Nissan)', max_length=100, verbose_name='Make')),
                ('model', models.CharField(help_text='Vehicle model (e.g., Corolla, Civic, Patrol)', max_length=100, verbose_name='Model')),
                ('year', models.IntegerField(help_text='Year the vehicle was manufactured', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Year of Manufacture')),
                ('vin', models.CharField(help_text='17-character unique vehicle identifier', max_length=17, unique=True, validators=[utils.validators.validate_vin], verbose_name='VIN (Vehicle Identification Number)')),
                ('registration_number', models.CharField(blank=True, help_text='Vehicle registration/license plate number (e.g., KAA 123A)', max_length=20, null=True, unique=True, validators=[utils.validators.validate_license_plate], verbose_name='Registration Number')),
                ('color', models.CharField(help_text='Exterior color', max_length=50, verbose_name='Color')),
                ('mileage', models.IntegerField(help_text='Current mileage in kilometers', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mileage (KM)')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='petrol', max_length=20, verbose_name='Fuel Type')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT')], default='manual', max_length=20, verbose_name='Transmission')),
                ('engine_size', models.CharField(blank=True, help_text='Engine capacity (e.g., 1.5L, 2000cc)', max_length=20, verbose_name='Engine Size')),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup Truck'), ('van', 'Van'), ('coupe', 'Coupe'), ('wagon', 'Station Wagon'), ('other', 'Other')], max_length=50, verbose_name='Body Type')),
                ('seats', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Number of Seats')),
                ('doors', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='Number of Doors')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20, verbose_name='Condition')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price at which vehicle was purchased', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Purchase Price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Current selling price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Selling Price')),
                ('deposit_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum deposit required for purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Deposit Required')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('repossessed', 'Repossessed'), ('auctioned', 'Auctioned'), ('maintenance', 'Under Maintenance')], db_index=True, default='available', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether vehicle is active in inventory', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Display as featured vehicle', verbose_name='Featured')),
                ('description', models.TextField(blank=True, help_text='Additional details about the vehicle', verbose_name='Description')),
                ('features', models.TextField(blank=True, help_text='Special features (e.g., AC, Power Steering, Sunroof)', verbose_name='Features')),
                ('location', models.CharField(blank=True, help_text='Where vehicle is currently located', max_length=200, verbose_name='Location')),
                ('purchase_date', models.DateField(help_text='Date vehicle was purchased/acquired', verbose_name='Purchase Date')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_sold', models.DateField(blank=True, null=True, verbose_name='Date Sold')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('repossessed', 'Repossessed'), ('auctioned', 'Auctioned'), ('maintenance', 'Under Maintenance')], max_length=20, verbose_name='Previous Status')),
                ('new_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('repossessed', 'Repossessed'), ('auctioned', 'Auctioned'), ('maintenance', 'Under Maintenance')], max_length=20, verbose_name='New Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the change', verbose_name='Notes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_changes', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle History',
                'verbose_name_plural': 'Vehicle History',
                'db_table': 'vehicle_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Vehicle photo', upload_to='vehicles/%Y/%m/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, help_text='Optional photo description', max_length=200, verbose_name='Caption')),
                ('is_primary', models.BooleanField(default=False, help_text='Main photo to display', verbose_name='Primary Photo')),
                ('order', models.IntegerField(default=0, help_text='Order to display photos', verbose_name='Display Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_photos_uploaded', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Photo',
                'verbose_name_plural': 'Vehicle Photos',
                'db_table': 'vehicle_photos',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', '-date_added'], name='vehicles_status_357efb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model'], name='vehicles_make_17021f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicles_vin_42311c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicles_registr_eb8990_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active', 'status'], name='vehicles_is_acti_7d29b3_idx'),
        ),
    ]
