# Generated by Django 5.0.7 on 2026-05-09 13:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='clearance_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Port/customs clearance cost', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Clearance Cost'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='commission_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission or agent fees', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Commission Cost'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='duty_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Import duty cost', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Duty Cost'),
        ),
        migrations.CreateModel(
            name='VehicleExtraCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the cost', max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_extra_costs_added', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_costs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Extra Cost',
                'verbose_name_plural': 'Vehicle Extra Costs',
                'db_table': 'vehicle_extra_costs',
                'ordering': ['-date_added'],
            },
        ),
    ]
