# Generated by Django 5.1 on 2026-05-06 22:30

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(help_text='Unique vehicle identifier (can include hyphens)', max_length=100, unique=True, validators=[utils.validators.validate_vin], verbose_name='VIN (Vehicle Identification Number)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(help_text='Year the vehicle was manufactured', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Year of Manufacture'),
        ),
    ]
