# Generated by Django 5.0.7 on 2026-05-10 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_chassis_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location_moved_by',
            field=models.ForeignKey(blank=True, help_text='Driver or staff member who moved the vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_moved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location_moved_date',
            field=models.DateField(blank=True, help_text='Date the vehicle was moved to its current location', null=True, verbose_name='Location Move Date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, choices=[('yard_1', 'Yard 1'), ('yard_2', 'Yard 2'), ('yard_3', 'Yard 3'), ('showroom', 'Showroom')], help_text='Current location of the vehicle', max_length=200, verbose_name='Location'),
        ),
    ]
