# Generated by Django 5.0.7 on 2026-05-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_location_moved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(blank=True, choices=[('yard_1', 'Yard 1'), ('yard_2', 'Yard 2'), ('yard_3', 'Yard 3'), ('showroom', 'Showroom')], max_length=200, verbose_name='From Location')),
                ('to_location', models.CharField(choices=[('yard_1', 'Yard 1'), ('yard_2', 'Yard 2'), ('yard_3', 'Yard 3'), ('showroom', 'Showroom')], max_length=200, verbose_name='To Location')),
                ('moved_date', models.DateField(blank=True, null=True, verbose_name='Moved Date')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_location_moves', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Location History',
                'verbose_name_plural': 'Vehicle Location History',
                'db_table': 'vehicle_location_history',
                'ordering': ['-moved_date', '-recorded_at'],
            },
        ),
    ]
