# Generated by Django 5.0.7 on 2026-05-10 08:08

from django.db import migrations, models


def copy_driver_details_forward(apps, schema_editor):
    Vehicle = apps.get_model('vehicles', 'Vehicle')
    VehicleLocationHistory = apps.get_model('vehicles', 'VehicleLocationHistory')

    def build_name(user):
        full_name = f"{(user.first_name or '').strip()} {(user.last_name or '').strip()}".strip()
        return full_name or user.email or ''

    for vehicle in Vehicle.objects.select_related('location_moved_by').all():
        moved_by = getattr(vehicle, 'location_moved_by', None)
        if not moved_by:
            continue

        profile = getattr(moved_by, 'profile', None)
        vehicle.location_driver_name = build_name(moved_by)
        vehicle.location_driver_phone = moved_by.phone or ''
        vehicle.location_driver_id_number = getattr(profile, 'national_id', '') or moved_by.employee_id or ''
        vehicle.save(update_fields=['location_driver_name', 'location_driver_phone', 'location_driver_id_number'])

    for move in VehicleLocationHistory.objects.select_related('moved_by').all():
        moved_by = getattr(move, 'moved_by', None)
        if not moved_by:
            continue

        profile = getattr(moved_by, 'profile', None)
        move.driver_name = build_name(moved_by)
        move.driver_phone = moved_by.phone or ''
        move.driver_id_number = getattr(profile, 'national_id', '') or moved_by.employee_id or ''
        move.save(update_fields=['driver_name', 'driver_phone', 'driver_id_number'])


def copy_driver_details_backward(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehiclelocationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location_driver_id_number',
            field=models.CharField(blank=True, help_text='National ID or identification number of the driver', max_length=100, verbose_name='Driver ID Number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location_driver_name',
            field=models.CharField(blank=True, help_text='Name of the driver who moved the vehicle', max_length=200, verbose_name='Driver Name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location_driver_phone',
            field=models.CharField(blank=True, help_text='Phone number of the driver who moved the vehicle', max_length=50, verbose_name='Driver Phone Number'),
        ),
        migrations.AddField(
            model_name='vehiclelocationhistory',
            name='driver_id_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Driver ID Number'),
        ),
        migrations.AddField(
            model_name='vehiclelocationhistory',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Driver Name'),
        ),
        migrations.AddField(
            model_name='vehiclelocationhistory',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Driver Phone Number'),
        ),
        migrations.RunPython(copy_driver_details_forward, copy_driver_details_backward),
        migrations.RemoveField(
            model_name='vehicle',
            name='location_moved_by',
        ),
        migrations.RemoveField(
            model_name='vehiclelocationhistory',
            name='moved_by',
        ),
    ]
