# Generated by Django 5.0.7 on 2026-05-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_remove_vehicle_location_moved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocationhistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional reason or context for the move', verbose_name='Move Notes'),
        ),
    ]
