# Generated by Django 5.0.7 on 2026-06-07 22:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    connection = schema_editor.connection
    if connection.vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute(f"PRAGMA table_info({table_name})")
            return any(row[1] == column_name for row in cursor.fetchall())
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = %s AND column_name = %s
            """,
            [table_name, column_name],
        )
        return cursor.fetchone() is not None


def add_website_price_if_missing(apps, schema_editor):
    table_name = 'vehicles'
    column_name = 'website_price'

    if _column_exists(schema_editor, table_name, column_name):
        return

    # Build the field definition Django would have generated, then apply it manually.
    field = models.DecimalField(
        null=True,
        blank=True,
        max_digits=12,
        decimal_places=2,
        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
        verbose_name='Website Price',
        help_text='Public-facing vehicle price shown on the website',
    )
    field.set_attributes_from_name(column_name)

    Vehicle = apps.get_model('vehicles', 'Vehicle')
    schema_editor.add_field(Vehicle, field)


def remove_website_price_if_exists(apps, schema_editor):
    table_name = 'vehicles'
    column_name = 'website_price'

    if not _column_exists(schema_editor, table_name, column_name):
        return

    Vehicle = apps.get_model('vehicles', 'Vehicle')
    field = Vehicle._meta.get_field(column_name)
    schema_editor.remove_field(Vehicle, field)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehiclelocationhistory_notes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_website_price_if_missing,
                    reverse_code=remove_website_price_if_exists,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='vehicle',
                    name='website_price',
                    field=models.DecimalField(blank=True, decimal_places=2, help_text='Public-facing vehicle price shown on the website', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Website Price'),
                ),
            ],
        ),
    ]
