# Generated by Django 5.0.7 on 2026-06-07 22:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehiclelocationhistory_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='website_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Public-facing vehicle price shown on the website', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Website Price'),
        ),
    ]
