# Generated by Django 5.0.7 on 2026-06-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_website_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, choices=[('yard_1', 'Yard 1'), ('cfs', 'CFS'), ('yard_2', 'Yard 2'), ('yard_3', 'Yard 3'), ('showroom', 'Showroom')], help_text='Current location of the vehicle', max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='vehiclelocationhistory',
            name='from_location',
            field=models.CharField(blank=True, choices=[('yard_1', 'Yard 1'), ('cfs', 'CFS'), ('yard_2', 'Yard 2'), ('yard_3', 'Yard 3'), ('showroom', 'Showroom')], max_length=200, verbose_name='From Location'),
        ),
        migrations.AlterField(
            model_name='vehiclelocationhistory',
            name='to_location',
            field=models.CharField(choices=[('yard_1', 'Yard 1'), ('cfs', 'CFS'), ('yard_2', 'Yard 2'), ('yard_3', 'Yard 3'), ('showroom', 'Showroom')], max_length=200, verbose_name='To Location'),
        ),
    ]
