# Generated by Django 5.1 on 2026-06-11 20:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_add_other_payment_details_to_clientvehicle'),
        ('vehicles', '0010_alter_vehicle_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clearing Agent',
                'verbose_name_plural': 'Clearing Agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackerProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracker Provider',
                'verbose_name_plural': 'Tracker Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount (KES)')),
                ('date', models.DateField(verbose_name='Clearance Date')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10, verbose_name='Payment Status')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_records', to='vehicles.vehicle')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearance_records', to='vehicles.clearingagent')),
            ],
            options={
                'verbose_name': 'Clearance Record',
                'verbose_name_plural': 'Clearance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrackerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_name', models.CharField(max_length=200, verbose_name='Tracker Name')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('buying_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Buying Price (KES)')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Selling Price (KES)')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('dealer_payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10, verbose_name='Dealer Payment Status')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_records', to='clients.clientvehicle')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracker_records', to='vehicles.trackerprovider')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_records', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Tracker Record',
                'verbose_name_plural': 'Tracker Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
