# Generated by Django 5.1 on 2026-06-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_clearingagent_trackerprovider_clearancerecord_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackerProvider',
            new_name='TrackerAgent',
        ),
        migrations.AlterModelOptions(
            name='trackeragent',
            options={'ordering': ['name'], 'verbose_name': 'Tracker Agent', 'verbose_name_plural': 'Tracker Agents'},
        ),
        migrations.RenameField(
            model_name='trackerrecord',
            old_name='provider',
            new_name='agent',
        ),
    ]
