# Generated by Django 5.1 on 2026-06-25 14:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _drop_leftover_postgres_objects(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        for statement in (
            "DROP TABLE IF EXISTS vehicles_japansupplierrecord CASCADE;",
            "DROP TABLE IF EXISTS vehicles_japansupplierpayment CASCADE;",
            "DROP TABLE IF EXISTS vehicles_japansupplier CASCADE;",
            "DROP TYPE IF EXISTS vehicles_japansupplierrecord CASCADE;",
            "DROP TYPE IF EXISTS vehicles_japansupplierpayment CASCADE;",
            "DROP TYPE IF EXISTS vehicles_japansupplier CASCADE;",
        ):
            cursor.execute(statement)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_broker_brokerpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop any leftover types/tables from a previous failed migration attempt (PostgreSQL only;
        # CASCADE is not valid SQLite syntax, so this is a no-op on SQLite).
        migrations.RunPython(_drop_leftover_postgres_objects, migrations.RunPython.noop),
        migrations.CreateModel(
            name='JapanSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, default='Japan', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Japan Supplier',
                'verbose_name_plural': 'Japan Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JapanSupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount (KES)')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer / SWIFT'), ('mpesa', 'M-Pesa'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference / Receipt No.')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='japan_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vehicles.japansupplier')),
            ],
            options={
                'verbose_name': 'Japan Supplier Payment',
                'verbose_name_plural': 'Japan Supplier Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JapanSupplierRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Purchase Price (KES)')),
                ('date', models.DateField(verbose_name='Purchase Date')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10, verbose_name='Payment Status')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_records', to='vehicles.japansupplier')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='japan_supplier_record', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Japan Supplier Record',
                'verbose_name_plural': 'Japan Supplier Records',
                'ordering': ['-date'],
            },
        ),
    ]
