# Generated by Django 5.1 on 2026-06-25 15:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_japan_supplier_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japansupplierrecord',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Purchase Price (USD)'),
        ),
    ]
