# Generated by Django 5.1 on 2026-06-26 06:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_alter_japansupplierrecord_purchase_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount (KES)')),
                ('direction', models.CharField(choices=[('in', 'Money In'), ('out', 'Money Out')], max_length=3, verbose_name='Direction')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Ledger Entry',
                'verbose_name_plural': 'Manual Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
