# Generated by Django 5.1 on 2026-06-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_manual_ledger_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, choices=[('yard_1', 'Yard 1'), ('cfs', 'CFS'), ('cfs1', 'CFS 1'), ('cfs2', 'CFS 2'), ('japan', 'Japan'), ('yard_2', 'Yard 2'), ('yard_3', 'Yard 3'), ('showroom', 'Showroom')], help_text='Current location of the vehicle', max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='vehiclelocationhistory',
            name='from_location',
            field=models.CharField(blank=True, choices=[('yard_1', 'Yard 1'), ('cfs', 'CFS'), ('cfs1', 'CFS 1'), ('cfs2', 'CFS 2'), ('japan', 'Japan'), ('yard_2', 'Yard 2'), ('yard_3', 'Yard 3'), ('showroom', 'Showroom')], max_length=200, verbose_name='From Location'),
        ),
        migrations.AlterField(
            model_name='vehiclelocationhistory',
            name='to_location',
            field=models.CharField(choices=[('yard_1', 'Yard 1'), ('cfs', 'CFS'), ('cfs1', 'CFS 1'), ('cfs2', 'CFS 2'), ('japan', 'Japan'), ('yard_2', 'Yard 2'), ('yard_3', 'Yard 3'), ('showroom', 'Showroom')], max_length=200, verbose_name='To Location'),
        ),
    ]
