# Generated by Django 5.1 on 2026-07-02 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_clerk_can_record_transactions'),
        ('vehicles', '0019_alter_vehicle_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerpayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Financial account this payment was paid from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_payments', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='clearingagentpayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Financial account this payment was paid from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearing_agent_payments', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='japansupplierpayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Financial account this payment was paid from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='japan_supplier_payments', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='trackeragentpayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Financial account this payment was paid from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_agent_payments', to='finance.financialaccount'),
        ),
    ]
