# Generated by Django 5.1 on 2026-07-04 11:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vehicles', '0019_alter_vehicle_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(help_text='Name of the borrower. Auto-filled when linked below; editable for outside parties.', max_length=200, verbose_name='Borrower')),
                ('borrower_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Principal Amount (KES)')),
                ('date_issued', models.DateField(default=django.utils.timezone.now, verbose_name='Date Issued')),
                ('expected_repayment_date', models.DateField(blank=True, null=True, verbose_name='Expected Repayment Date')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='Purpose')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('partially_repaid', 'Partially Repaid'), ('fully_repaid', 'Fully Repaid'), ('written_off', 'Written Off')], default='outstanding', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower_content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'clients'), ('model', 'client')), models.Q(('app_label', 'vehicles'), ('model', 'broker')), models.Q(('app_label', 'vehicles'), ('model', 'trackeragent')), models.Q(('app_label', 'vehicles'), ('model', 'clearingagent')), models.Q(('app_label', 'vehicles'), ('model', 'japansupplier')), models.Q(('app_label', 'insurance'), ('model', 'insuranceagent')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_loans_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Loan',
                'verbose_name_plural': 'Business Loans',
                'ordering': ['-date_issued', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount (KES)')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference / Receipt No.')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='vehicles.businessloan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_loan_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Loan Repayment',
                'verbose_name_plural': 'Business Loan Repayments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
