# Generated by Django 5.1 on 2026-07-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_businessloan_businessloanrepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualledgerentry',
            name='direction',
            field=models.CharField(choices=[('in', 'Debit'), ('out', 'Credit')], max_length=3, verbose_name='Direction'),
        ),
    ]
