# Generated by Django 5.1 on 2026-07-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_alter_manualledgerentry_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='allow_photo_downloads',
            field=models.BooleanField(default=True, help_text="Allow website visitors to download this vehicle's public photos", verbose_name='Allow Photo Downloads'),
        ),
        migrations.AddField(
            model_name='vehiclephoto',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this photo has been downloaded from the website', verbose_name='Download Count'),
        ),
        migrations.AddField(
            model_name='vehiclephoto',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public photos appear on the website and can be downloaded; internal photos are visible to staff only', verbose_name='Public Photo'),
        ),
    ]
