# Generated by Django 5.1 on 2026-07-17 16:40
#
# Written defensively: the deploy pipeline can run `migrate` twice in
# parallel (container entrypoint + `make update` exec), so a losing racer
# may find these columns already present without a django_migrations
# record. Each column is therefore added only if it does not already
# exist. Plain ALTER TABLE ADD COLUMN is used deliberately —
# schema_editor.add_field() would rebuild the whole table on SQLite from
# the historical model state and silently drop sibling columns that were
# added by the racing migrate run.

from django.db import migrations, models

COLUMNS = [
    # (table, column, SQL definition valid on both SQLite and PostgreSQL)
    ('vehicles', 'allow_photo_downloads', 'boolean NOT NULL DEFAULT TRUE'),
    ('vehicle_photos', 'download_count', 'integer NOT NULL DEFAULT 0'),
    ('vehicle_photos', 'is_public', 'boolean NOT NULL DEFAULT TRUE'),
]


def add_missing_columns(apps, schema_editor):
    connection = schema_editor.connection
    quote = schema_editor.quote_name
    for table, column, definition in COLUMNS:
        with connection.cursor() as cursor:
            existing = {
                col.name
                for col in connection.introspection.get_table_description(cursor, table)
            }
        if column in existing:
            continue
        schema_editor.execute(
            f'ALTER TABLE {quote(table)} ADD COLUMN {quote(column)} {definition}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_alter_manualledgerentry_direction'),
    ]

    operations = [
        migrations.RunPython(add_missing_columns, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='vehicle',
                    name='allow_photo_downloads',
                    field=models.BooleanField(default=True, help_text="Allow website visitors to download this vehicle's public photos", verbose_name='Allow Photo Downloads'),
                ),
                migrations.AddField(
                    model_name='vehiclephoto',
                    name='download_count',
                    field=models.PositiveIntegerField(default=0, help_text='Number of times this photo has been downloaded from the website', verbose_name='Download Count'),
                ),
                migrations.AddField(
                    model_name='vehiclephoto',
                    name='is_public',
                    field=models.BooleanField(default=True, help_text='Public photos appear on the website and can be downloaded; internal photos are visible to staff only', verbose_name='Public Photo'),
                ),
            ],
            database_operations=[],
        ),
    ]
