# Generated by Django 5.1.11 on 2025-08-16 06:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales Representative'), ('accountant', 'Accountant'), ('auctioneer', 'Auctioneer'), ('manager', 'Manager'), ('clerk', 'Clerk')], max_length=20)),
                ('module_name', models.CharField(choices=[('dashboard', 'Dashboard'), ('vehicles', 'Vehicle Management'), ('clients', 'Client Management'), ('payments', 'Payment Management'), ('payroll', 'Payroll Management'), ('expenses', 'Expense Tracking'), ('auctions', 'Auction Management'), ('insurance', 'Insurance Management'), ('notifications', 'Notifications'), ('documents', 'Document Management'), ('reports', 'Reports'), ('audit', 'Audit Logs')], max_length=50)),
                ('access_level', models.CharField(choices=[('none', 'No Access'), ('read', 'Read Only'), ('write', 'Read & Write'), ('full', 'Full Access')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warranty_type', models.CharField(choices=[('manufacturer', 'Manufacturer Warranty'), ('dealer', 'Dealer Warranty'), ('extended', 'Extended Warranty'), ('parts', 'Parts Warranty'), ('service', 'Service Warranty')], max_length=20)),
                ('warranty_provider', models.CharField(max_length=100)),
                ('warranty_number', models.CharField(max_length=50, unique=True)),
                ('coverage_description', models.TextField()),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mileage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('claimed', 'Claimed'), ('void', 'Void')], default='active', max_length=20)),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('claim_description', models.TextField(blank=True)),
                ('claim_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20)),
                ('warranty_document', models.FileField(blank=True, null=True, upload_to='warranties/')),
                ('claim_documents', models.FileField(blank=True, null=True, upload_to='warranty_claims/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Warranty Tracking',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales Representative'), ('accountant', 'Accountant'), ('auctioneer', 'Auctioneer'), ('manager', 'Manager'), ('clerk', 'Clerk')], default='clerk', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active_employee', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousFinancial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('financial_type', models.CharField(choices=[('discount', 'Discount'), ('after_sale_repair', 'After-Sale Repair'), ('after_sale_service', 'After-Sale Service'), ('promotional_expense', 'Promotional Expense'), ('warranty_claim', 'Warranty Claim'), ('refund', 'Refund'), ('adjustment', 'Financial Adjustment'), ('commission', 'Sales Commission'), ('incentive', 'Sales Incentive'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approval_required', models.BooleanField(default=True)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='misc_financials/')),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_misc_financials', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_misc_financials', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='misc_financials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miscellaneous Financial',
                'verbose_name_plural': 'Miscellaneous Financials',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
