# Generated by Django 5.1.12 on 2025-09-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales Representative'), ('accountant', 'Accountant'), ('auctioneer', 'Auctioneer'), ('manager', 'Manager'), ('clerk', 'Clerk'), ('client', 'Client')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales Representative'), ('accountant', 'Accountant'), ('auctioneer', 'Auctioneer'), ('manager', 'Manager'), ('clerk', 'Clerk'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
