# Generated by Django 5.1 on 2026-07-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Financial account this expense was paid from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.financialaccount'),
        ),
    ]
