# Generated by Django 5.1 on 2026-07-19 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('payroll', '0005_salary_commission_amount_commission_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='related_deduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='payroll.deduction'),
        ),
        migrations.AddField(
            model_name='expense',
            name='related_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='payroll.loan'),
        ),
        migrations.AddField(
            model_name='expense',
            name='related_payslip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='payroll.payslip'),
        ),
    ]
