# Generated by Django 5.1 on 2026-07-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_related_deduction_expense_related_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT', 'Debit — Money Out'), ('CREDIT', 'Credit — Refund / Reversal')], default='DEBIT', help_text='Debit records money spent; Credit records a refund or reversal that reduces the ledger balance.', max_length=10),
        ),
    ]
