# Generated by Django 5.1 on 2025-10-03 07:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('financial', 'Financial Report'), ('vehicle', 'Vehicle Report'), ('client', 'Client Report'), ('auction', 'Auction Report'), ('payment', 'Payment Report'), ('expense', 'Expense Report'), ('payroll', 'Payroll Report'), ('insurance', 'Insurance Report'), ('repossession', 'Repossession Report'), ('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('performance', 'Performance Report'), ('custom', 'Custom Report')], max_length=50)),
                ('layout', models.CharField(default='standard', help_text='standard, detailed, summary, etc.', max_length=50)),
                ('columns', models.JSONField(blank=True, default=list, help_text='List of columns to include')),
                ('grouping', models.JSONField(blank=True, default=dict, help_text='Grouping configuration')),
                ('sorting', models.JSONField(blank=True, default=dict, help_text='Sorting configuration')),
                ('aggregations', models.JSONField(blank=True, default=list, help_text='Aggregation functions to apply')),
                ('header_template', models.TextField(blank=True)),
                ('footer_template', models.TextField(blank=True)),
                ('css_styles', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('financial', 'Financial Report'), ('vehicle', 'Vehicle Report'), ('client', 'Client Report'), ('auction', 'Auction Report'), ('payment', 'Payment Report'), ('expense', 'Expense Report'), ('payroll', 'Payroll Report'), ('insurance', 'Insurance Report'), ('repossession', 'Repossession Report'), ('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('performance', 'Performance Report'), ('custom', 'Custom Report')], db_index=True, max_length=50)),
                ('query_config', models.JSONField(blank=True, default=dict, help_text='Query configuration and filters')),
                ('date_range_type', models.CharField(default='last_30_days', help_text='last_7_days, last_30_days, last_quarter, last_year, custom, etc.', max_length=50)),
                ('custom_date_from', models.DateField(blank=True, null=True)),
                ('custom_date_to', models.DateField(blank=True, null=True)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=20)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('include_details', models.BooleanField(default=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='once', max_length=20)),
                ('schedule_time', models.TimeField(blank=True, help_text='Time to run scheduled report', null=True)),
                ('schedule_day', models.IntegerField(blank=True, help_text='Day of month for monthly reports', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('email_recipients', models.TextField(blank=True, help_text='Additional email addresses (comma-separated)')),
                ('send_email', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Allow all users to view this report')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('last_execution_status', models.CharField(blank=True, max_length=20)),
                ('average_execution_time', models.DecimalField(blank=True, decimal_places=2, help_text='Average execution time in seconds', max_digits=8, null=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='subscribed_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('widget_type', models.CharField(choices=[('metric', 'Metric Card'), ('chart', 'Chart'), ('table', 'Table'), ('list', 'List'), ('gauge', 'Gauge'), ('trend', 'Trend Line')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('area', 'Area Chart')], max_length=20)),
                ('data_source', models.CharField(help_text='Model or data source', max_length=100)),
                ('query_config', models.JSONField(blank=True, default=dict, help_text='Query configuration')),
                ('refresh_interval', models.IntegerField(default=300, help_text='Refresh interval in seconds')),
                ('width', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('height', models.IntegerField(default=300)),
                ('order', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_widgets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_widgets', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.report')),
            ],
            options={
                'verbose_name': 'Report Widget',
                'verbose_name_plural': 'Report Widgets',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('custom_parameters', models.JSONField(blank=True, default=dict, help_text="User's custom parameters")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('is_scheduled', models.BooleanField(default=False, help_text='Was this execution triggered by schedule?')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.DecimalField(blank=True, decimal_places=2, help_text='Execution time in seconds', max_digits=8, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('output_format', models.CharField(max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Report result data/summary')),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Execution parameters')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.report')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', '-created_at'], name='reports_rep_report__5fe094_idx'), models.Index(fields=['status', '-created_at'], name='reports_rep_status_6cfda6_idx'), models.Index(fields=['triggered_by'], name='reports_rep_trigger_ae92f3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'is_active'], name='reports_rep_report__a0ff1c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_scheduled', 'next_run'], name='reports_rep_is_sche_2d0876_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by'], name='reports_rep_created_61f2ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedreport',
            unique_together={('user', 'report')},
        ),
    ]
