# Generated by Django 5.1 on 2026-06-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('financial', 'Financial Report'), ('vehicle', 'Vehicle Report'), ('client', 'Client Report'), ('auction', 'Auction Report'), ('payment', 'Payment Report'), ('company_payout', 'Company Payout Report'), ('expense', 'Expense Report'), ('payroll', 'Payroll Report'), ('insurance', 'Insurance Report'), ('repossession', 'Repossession Report'), ('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('performance', 'Performance Report'), ('custom', 'Custom Report')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('financial', 'Financial Report'), ('vehicle', 'Vehicle Report'), ('client', 'Client Report'), ('auction', 'Auction Report'), ('payment', 'Payment Report'), ('company_payout', 'Company Payout Report'), ('expense', 'Expense Report'), ('payroll', 'Payroll Report'), ('insurance', 'Insurance Report'), ('repossession', 'Repossession Report'), ('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('performance', 'Performance Report'), ('custom', 'Custom Report')], max_length=50),
        ),
    ]
