# Generated by Django 5.1 on 2025-10-03 07:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repossession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repossession_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('PAYMENT_DEFAULT', 'Payment Default'), ('BREACH_OF_CONTRACT', 'Breach of Contract'), ('INSURANCE_LAPSE', 'Insurance Lapse'), ('UNAUTHORIZED_USE', 'Unauthorized Use'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NOTICE_SENT', 'Notice Sent'), ('IN_PROGRESS', 'In Progress'), ('VEHICLE_RECOVERED', 'Vehicle Recovered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=20)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, help_text='Total amount owed', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payments_missed', models.PositiveIntegerField(default=0)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('initiated_date', models.DateField(default=django.utils.timezone.now)),
                ('notice_sent_date', models.DateField(blank=True, null=True)),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('last_known_location', models.TextField(blank=True)),
                ('current_location', models.TextField(blank=True, help_text='Current location of vehicle (if recovered)')),
                ('recovery_method', models.CharField(blank=True, help_text='How the vehicle was recovered', max_length=100)),
                ('recovery_agent', models.CharField(blank=True, max_length=200)),
                ('legal_notice_sent', models.BooleanField(default=False)),
                ('legal_notice_date', models.DateField(blank=True, null=True)),
                ('court_order_obtained', models.BooleanField(default=False)),
                ('court_order_date', models.DateField(blank=True, null=True)),
                ('court_order_number', models.CharField(blank=True, max_length=100)),
                ('recovery_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('storage_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('legal_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('resolution_type', models.CharField(blank=True, choices=[('PAID_IN_FULL', 'Paid in Full'), ('AUCTIONED', 'Vehicle Auctioned'), ('RETURNED', 'Returned to Client'), ('WRITTEN_OFF', 'Written Off'), ('OTHER', 'Other')], max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Agent/officer assigned to this repossession', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_repossessions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repossessions', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repossessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repossessions', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Repossession',
                'verbose_name_plural': 'Repossessions',
                'ordering': ['-initiated_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepossessionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_method', models.CharField(choices=[('PHONE', 'Phone Call'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('VISIT', 'In-Person Visit'), ('LETTER', 'Letter')], max_length=20)),
                ('contacted_person', models.CharField(help_text='Name of person contacted', max_length=200)),
                ('outcome', models.CharField(choices=[('SUCCESSFUL', 'Successful Contact'), ('NO_ANSWER', 'No Answer'), ('REFUSED', 'Refused to Engage'), ('PARTIAL', 'Partial Information'), ('VOICEMAIL', 'Left Voicemail'), ('PROMISE_TO_PAY', 'Promise to Pay'), ('OTHER', 'Other')], max_length=20)),
                ('discussion_summary', models.TextField()),
                ('next_action', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repossession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='repossessions.repossession')),
            ],
            options={
                'verbose_name': 'Client Contact',
                'verbose_name_plural': 'Client Contacts',
                'ordering': ['-contact_date'],
            },
        ),
        migrations.CreateModel(
            name='RepossessionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NOTICE', 'Repossession Notice'), ('COURT_ORDER', 'Court Order'), ('POLICE_REPORT', 'Police Report'), ('RECOVERY_REPORT', 'Recovery Report'), ('LEGAL_LETTER', 'Legal Letter'), ('PHOTO', 'Photo Evidence'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='repossessions/documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('repossession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='repossessions.repossession')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repossession Document',
                'verbose_name_plural': 'Repossession Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RepossessionExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('RECOVERY', 'Recovery Fee'), ('TOWING', 'Towing Fee'), ('STORAGE', 'Storage Fee'), ('LEGAL', 'Legal Fee'), ('COURT', 'Court Fee'), ('TRANSPORT', 'Transport'), ('DOCUMENTATION', 'Documentation'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repossession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='repossessions.repossession')),
            ],
            options={
                'verbose_name': 'Repossession Expense',
                'verbose_name_plural': 'Repossession Expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='RepossessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_type', models.CharField(blank=True, choices=[('UPDATE', 'Status Update'), ('CONTACT', 'Client Contact'), ('LOCATION', 'Location Info'), ('LEGAL', 'Legal Action'), ('RECOVERY', 'Recovery Attempt'), ('OTHER', 'Other')], max_length=20)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repossession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='repossessions.repossession')),
            ],
            options={
                'verbose_name': 'Repossession Note',
                'verbose_name_plural': 'Repossession Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepossessionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('FIRST_NOTICE', 'First Notice'), ('SECOND_NOTICE', 'Second Notice'), ('FINAL_NOTICE', 'Final Notice'), ('LEGAL_NOTICE', 'Legal Notice'), ('COURT_SUMMONS', 'Court Summons')], max_length=20)),
                ('notice_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('POST', 'Postal Mail'), ('HAND_DELIVERY', 'Hand Delivery'), ('SMS', 'SMS'), ('COURIER', 'Courier')], max_length=20)),
                ('delivery_address', models.TextField()),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=200)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Notice content/message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repossession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='repossessions.repossession')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repossession Notice',
                'verbose_name_plural': 'Repossession Notices',
                'ordering': ['-notice_date'],
            },
        ),
        migrations.CreateModel(
            name='RepossessionRecoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField(help_text='Location where attempt was made')),
                ('agent_name', models.CharField(max_length=200)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('result', models.CharField(choices=[('SUCCESSFUL', 'Vehicle Recovered'), ('NOT_FOUND', 'Vehicle Not Found'), ('ACCESS_DENIED', 'Access Denied'), ('CONFRONTATION', 'Confrontation Occurred'), ('POLICE_CALLED', 'Police Involvement'), ('POSTPONED', 'Attempt Postponed'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(help_text='Details of the recovery attempt')),
                ('police_involved', models.BooleanField(default=False)),
                ('police_report_number', models.CharField(blank=True, max_length=100)),
                ('vehicle_condition', models.TextField(blank=True, help_text='Condition of vehicle if recovered')),
                ('cost_incurred', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repossession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_attempts', to='repossessions.repossession')),
            ],
            options={
                'verbose_name': 'Recovery Attempt',
                'verbose_name_plural': 'Recovery Attempts',
                'ordering': ['-attempt_date'],
            },
        ),
        migrations.CreateModel(
            name='RepossessionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repossession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='repossessions.repossession')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='repossession',
            index=models.Index(fields=['status', 'initiated_date'], name='repossessio_status_eb7d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='repossession',
            index=models.Index(fields=['vehicle', 'status'], name='repossessio_vehicle_6b7d25_idx'),
        ),
        migrations.AddIndex(
            model_name='repossession',
            index=models.Index(fields=['client', 'status'], name='repossessio_client__eed250_idx'),
        ),
    ]
