# Generated by Django 5.0.7 on 2026-05-11 12:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repossessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repossession',
            name='additional_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional repossession-related costs to carry into repricing', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
