# Generated by Django 5.0.7 on 2026-05-11 12:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repossessions', '0002_repossession_additional_costs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepossessionAdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('TOWING', 'Towing'), ('STORAGE', 'Storage'), ('TRANSPORT', 'Transport'), ('LEGAL', 'Legal'), ('AUCTION', 'Auction Preparation'), ('REPAIR', 'Repair/Maintenance'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repossession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_cost_items', to='repossessions.repossession')),
            ],
            options={
                'verbose_name': 'Repossession Additional Cost',
                'verbose_name_plural': 'Repossession Additional Costs',
                'ordering': ['created_at'],
            },
        ),
    ]
