# Generated by Django 5.0.7 on 2026-06-06 13:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repossessions', '0003_repossessionadditionalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='repossession',
            name='contracted_auctioneer_id',
            field=models.CharField(blank=True, help_text='ID number of the contracted auctioneer', max_length=100),
        ),
        migrations.AddField(
            model_name='repossession',
            name='contracted_auctioneer_name',
            field=models.CharField(blank=True, help_text='Name of the contracted auctioneer', max_length=200),
        ),
        migrations.AddField(
            model_name='repossession',
            name='contracted_auctioneer_no',
            field=models.CharField(blank=True, help_text='Phone/contact number of the contracted auctioneer', max_length=30),
        ),
        migrations.AlterField(
            model_name='repossession',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount owed', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
