# Generated by Django 5.1 on 2025-10-03 07:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insurance provider name', max_length=200, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number', max_length=100, null=True)),
                ('phone_primary', models.CharField(help_text='Primary contact phone', max_length=15)),
                ('phone_secondary', models.CharField(blank=True, help_text='Secondary contact phone', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Website URL', null=True)),
                ('physical_address', models.TextField(help_text='Physical office address')),
                ('postal_address', models.CharField(blank=True, help_text='Postal address', max_length=200, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('contact_person_name', models.CharField(blank=True, help_text='Contact person name', max_length=200, null=True)),
                ('contact_person_phone', models.CharField(blank=True, help_text='Contact person phone', max_length=15, null=True)),
                ('contact_person_email', models.EmailField(blank=True, help_text='Contact person email', max_length=254, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(help_text='Insurance policy number', max_length=100, unique=True)),
                ('policy_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('third_party', 'Third Party'), ('third_party_fire_theft', 'Third Party Fire & Theft')], default='comprehensive', help_text='Type of insurance coverage', max_length=50)),
                ('start_date', models.DateField(help_text='Policy start date')),
                ('end_date', models.DateField(help_text='Policy expiry date')),
                ('premium_amount', models.DecimalField(decimal_places=2, help_text='Insurance premium amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sum_insured', models.DecimalField(decimal_places=2, help_text='Sum insured/vehicle value', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('excess_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Excess/deductible amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('certificate', models.FileField(blank=True, help_text='Insurance certificate file', null=True, upload_to='insurance/certificates/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('renewed', 'Renewed')], default='active', help_text='Policy status', max_length=20)),
                ('is_renewed', models.BooleanField(default=False, help_text='Whether this policy has been renewed')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether expiry reminder has been sent')),
                ('reminder_sent_date', models.DateField(blank=True, help_text='Date reminder was sent', null=True)),
                ('coverage_details', models.TextField(blank=True, help_text='Coverage details and terms', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client/owner of the vehicle (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='clients.client')),
                ('created_by', models.ForeignKey(help_text='User who created this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance_policies', to=settings.AUTH_USER_MODEL)),
                ('renewed_policy', models.ForeignKey(blank=True, help_text='Reference to renewed policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_policy', to='insurance.insurancepolicy')),
                ('vehicle', models.ForeignKey(help_text='Vehicle covered by this policy', on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='vehicles.vehicle')),
                ('provider', models.ForeignKey(help_text='Insurance provider', on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.insuranceprovider')),
            ],
            options={
                'verbose_name': 'Insurance Policy',
                'verbose_name_plural': 'Insurance Policies',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date payment was made')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('direct_debit', 'Direct Debit')], default='cash', help_text='Method of payment', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, help_text='Payment receipt number', max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_insurance_payments', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='Insurance policy this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance.insurancepolicy')),
            ],
            options={
                'verbose_name': 'Insurance Payment',
                'verbose_name_plural': 'Insurance Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_date'], name='insurance_i_payment_0921f5_idx'), models.Index(fields=['policy'], name='insurance_i_policy__b6b85b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(help_text='Claim reference number', max_length=100, unique=True)),
                ('claim_type', models.CharField(choices=[('accident', 'Accident'), ('theft', 'Theft'), ('fire', 'Fire'), ('vandalism', 'Vandalism'), ('natural_disaster', 'Natural Disaster'), ('other', 'Other')], help_text='Type of claim', max_length=50)),
                ('incident_date', models.DateField(help_text='Date of incident')),
                ('claim_date', models.DateField(default=django.utils.timezone.now, help_text='Date claim was filed')),
                ('incident_location', models.CharField(help_text='Location where incident occurred', max_length=500)),
                ('incident_description', models.TextField(help_text='Detailed description of the incident')),
                ('police_report_number', models.CharField(blank=True, help_text='Police report/OB number (if applicable)', max_length=100, null=True)),
                ('claimed_amount', models.DecimalField(decimal_places=2, help_text='Amount claimed', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount approved by insurer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually settled/paid', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('excess_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Excess amount paid by client', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled')], default='pending', help_text='Claim status', max_length=20)),
                ('status_date', models.DateField(auto_now=True, help_text='Date of last status change')),
                ('settlement_date', models.DateField(blank=True, help_text='Date claim was settled', null=True)),
                ('assessor_name', models.CharField(blank=True, help_text='Insurance assessor name', max_length=200, null=True)),
                ('assessor_phone', models.CharField(blank=True, help_text='Assessor contact phone', max_length=15, null=True)),
                ('assessment_date', models.DateField(blank=True, help_text='Date of assessment', null=True)),
                ('assessment_report', models.FileField(blank=True, help_text='Assessment report file', null=True, upload_to='insurance/assessments/%Y/%m/')),
                ('supporting_documents', models.FileField(blank=True, help_text='Supporting documents (photos, receipts, etc.)', null=True, upload_to='insurance/claims/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes and updates', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(help_text='User who filed this claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_insurance_claims', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='Insurance policy for this claim', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insurancepolicy')),
            ],
            options={
                'verbose_name': 'Insurance Claim',
                'verbose_name_plural': 'Insurance Claims',
                'ordering': ['-claim_date'],
                'indexes': [models.Index(fields=['claim_number'], name='insurance_i_claim_n_de6fe8_idx'), models.Index(fields=['status'], name='insurance_i_status_497753_idx'), models.Index(fields=['claim_date'], name='insurance_i_claim_d_48be8f_idx'), models.Index(fields=['incident_date'], name='insurance_i_inciden_acf962_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='insuranceprovider',
            index=models.Index(fields=['name'], name='insurance_i_name_7acc67_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceprovider',
            index=models.Index(fields=['is_active'], name='insurance_i_is_acti_e328fc_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['policy_number'], name='insurance_i_policy__526337_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['start_date', 'end_date'], name='insurance_i_start_d_45fcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['status'], name='insurance_i_status_056465_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['vehicle'], name='insurance_i_vehicle_a1608a_idx'),
        ),
    ]
