# Generated by Django 5.0.7 on 2026-05-09 13:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='insurance_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual interest rate for payment plan (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Insurance Interest Rate (%)'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insurance_total_with_interest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated total including interest', max_digits=12, null=True, verbose_name='Total with Interest (KES)'),
        ),
        migrations.CreateModel(
            name='InsurancePaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(help_text='Installment number (1, 2, 3, etc.)')),
                ('due_date', models.DateField(help_text='Date this installment is due')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Amount due for this installment', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid for this installment', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('late_fee_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fees applied (0.1% per day, max 50% of amount due)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this installment has been paid')),
                ('payment_date', models.DateField(blank=True, help_text='Date payment was received', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, help_text='Insurance payment that fulfilled this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_schedules', to='insurance.insurancepayment')),
                ('policy', models.ForeignKey(help_text='Insurance policy this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='insurance_payment_schedules', to='insurance.insurancepolicy')),
            ],
            options={
                'verbose_name': 'Insurance Payment Schedule',
                'verbose_name_plural': 'Insurance Payment Schedules',
                'ordering': ['installment_number'],
                'indexes': [models.Index(fields=['due_date'], name='insurance_i_due_dat_9c2578_idx'), models.Index(fields=['is_paid'], name='insurance_i_is_paid_feaaa2_idx'), models.Index(fields=['policy', 'due_date'], name='insurance_i_policy__96e305_idx')],
                'unique_together': {('policy', 'installment_number')},
            },
        ),
    ]
