# Generated by Django 5.0.7 on 2026-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurancepolicy_insurance_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('flexible', 'Flexible Installments'), ('deduct_from_deposit', 'Deduct from Deposit')], default='full', help_text='How the client pays for insurance', max_length=30, verbose_name='Payment Type'),
        ),
    ]
