# Generated by Django 5.0.7 on 2026-05-10 19:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_add_payment_type_to_insurance_and_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Insurance premium amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
