# Generated by Django 5.0.7 on 2026-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_fix_premium_amount_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='vehicle_usage',
            field=models.CharField(choices=[('private', 'Private'), ('psv', 'PSV')], default='private', help_text='Vehicle usage category for the policy', max_length=20),
        ),
    ]
