# Generated by Django 5.0.7 on 2026-06-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insurancepolicy_vehicle_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprovider',
            name='phone_primary',
            field=models.CharField(blank=True, help_text='Primary contact phone', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='physical_address',
            field=models.TextField(blank=True, help_text='Physical office address', null=True),
        ),
    ]
