# Generated by Django 5.1 on 2026-06-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_insuranceprovider_phone_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_number', models.CharField(blank=True, help_text='Agent ID or license number', max_length=100, verbose_name='ID / License Number')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance Agent',
                'verbose_name_plural': 'Insurance Agents',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='dealer_payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='Whether we have paid the agent for this policy', max_length=10, verbose_name='Dealer Payment Status'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insurance_agent',
            field=models.ForeignKey(blank=True, help_text='Linked insurance agent (ledger)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='insurance.insuranceagent'),
        ),
    ]
