# Generated by Django 5.1 on 2026-06-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_insuranceagent_insurancepolicy_dealer_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='provider',
        ),
        migrations.DeleteModel(
            name='InsuranceProvider',
        ),
    ]
