# Generated by Django 5.1 on 2026-06-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_insurancepolicy_payment_method'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='insurancepolicy',
                    name='renewal_of',
                    field=models.ForeignKey(blank=True, help_text='The policy this was renewed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='insurance.insurancepolicy'),
                ),
            ],
        ),
    ]
