# Generated by Django 5.1 on 2026-07-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_insurancepolicy_renewal_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='deposit_payment_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Deposit Payment Location'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='deposit_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('equity_hoza', 'Equity Hoza'), ('dib_hoza', 'DIB Hoza'), ('coop_hoza', 'COOP Hoza'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('other', 'Other')], default='cash', max_length=30, verbose_name='Deposit Payment Method'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='deposit_splits_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of {method, amount, reference, location} when the deposit was split across methods', verbose_name='Deposit Split Payments (JSON)'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='deposit_transaction_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Deposit Transaction Reference'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='insurance_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('equity_hoza', 'Equity Hoza'), ('dib_hoza', 'DIB Hoza'), ('coop_hoza', 'COOP Hoza'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('other', 'Other')], default='cash', help_text='Method used to pay for insurance', max_length=30, verbose_name='Payment Method'),
        ),
    ]
