# Generated by Django 5.1 on 2026-07-02 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_clerk_can_record_transactions'),
        ('insurance', '0011_insurancepolicy_renewal_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceagentpayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Financial account this payment was paid from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_agent_payments', to='finance.financialaccount'),
        ),
    ]
