# Generated by Django 5.1 on 2026-07-24 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The raw question as typed by the user', max_length=300, verbose_name='Question Text')),
                ('keywords', models.CharField(blank=True, help_text='Space-separated content keywords extracted from the question', max_length=300, verbose_name='Tracked Keywords')),
                ('matched', models.BooleanField(default=False, help_text='Whether the assistant found an answer for this question', verbose_name='Matched')),
                ('question_id', models.CharField(blank=True, help_text='Registry id of the question that answered this query', max_length=50, verbose_name='Matched Question ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Match Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Asked At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Query',
                'verbose_name_plural': 'Assistant Queries',
                'db_table': 'assistant_queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
