# Generated by Django 5.1 on 2026-07-01 18:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0038_alter_client_status'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0013_payment_is_reversed_payment_reversal_reason_and_more'),
        ('vehicles', '0019_alter_vehicle_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Short unique account code, e.g. DIB-HOZA', max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('mpesa_paybill', 'M-Pesa Paybill'), ('mpesa_till', 'M-Pesa Till'), ('cash', 'Cash Account'), ('mobile_money', 'Mobile Money Account'), ('internal_wallet', 'Internal Wallet'), ('suspense', 'Suspense Account'), ('other', 'Other')], default='bank', max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('paybill_number', models.CharField(blank=True, max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=20)),
                ('business_shortcode', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opening_balance_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Default account suggested when recording new transactions')),
                ('allow_manual_transactions', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Account',
                'verbose_name_plural': 'Financial Accounts',
                'db_table': 'finance_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(default=django.utils.timezone.now)),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='finance.financialaccount')),
            ],
            options={
                'verbose_name': 'Account Reconciliation',
                'verbose_name_plural': 'Account Reconciliations',
                'db_table': 'finance_account_reconciliations',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('client_vehicle_payment', 'Client Vehicle Payment'), ('hire_purchase_instalment', 'Hire Purchase Instalment Payment'), ('vehicle_deposit', 'Vehicle Deposit'), ('insurance_payment', 'Insurance Payment'), ('tracker_payment', 'Tracker Payment'), ('clearance_payment', 'Clearance Payment'), ('auction_payment', 'Auction Payment'), ('mpesa_payment', 'M-Pesa Payment'), ('bank_deposit', 'Bank Deposit'), ('cash_deposit', 'Cash Deposit'), ('manual_credit_adjustment', 'Manual Credit Adjustment'), ('internal_transfer_received', 'Internal Transfer Received'), ('vehicle_purchase_cost', 'Vehicle Purchase Cost'), ('duty_payment', 'Duty Payment'), ('shipping_cost', 'Shipping Cost'), ('port_charges', 'Port Charges'), ('clearing_charges', 'Clearing Charges'), ('repair_expense', 'Repair Expense'), ('yard_expense', 'Yard Expense'), ('broker_commission', 'Broker Commission'), ('supplier_payment', 'Supplier Payment'), ('tracker_vendor_payment', 'Tracker Vendor Payment'), ('insurance_company_payment', 'Insurance Company Payment'), ('auctioneer_payment', 'Auctioneer Payment'), ('staff_expense', 'Staff-Related Expense'), ('bank_withdrawal', 'Bank Withdrawal'), ('cash_withdrawal', 'Cash Withdrawal'), ('manual_debit_adjustment', 'Manual Debit Adjustment'), ('internal_transfer_sent', 'Internal Transfer Sent'), ('reversal', 'Reversal'), ('correction', 'Correction'), ('opening_balance_adjustment', 'Opening Balance Adjustment'), ('suspense_allocation', 'Suspense Account Allocation'), ('bank_charge', 'Bank Charge'), ('refund', 'Refund'), ('overpayment_allocation', 'Overpayment Allocation')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('source_module', models.CharField(choices=[('payments', 'Payments'), ('expenses', 'Expenses'), ('vehicles', 'Vehicles'), ('clients', 'Clients'), ('auctions', 'Auctions'), ('repossessions', 'Repossessions'), ('insurance', 'Insurance'), ('trackers', 'Trackers'), ('clearance', 'Clearance'), ('payroll', 'Payroll'), ('manual', 'Manual Entry'), ('transfer', 'Internal Transfer'), ('suspense', 'Suspense'), ('reconciliation', 'Reconciliation'), ('other', 'Other')], default='manual', max_length=30)),
                ('related_party_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_party_label', models.CharField(blank=True, help_text='Free-text supplier/vendor name, used when no linked record applies', max_length=200)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('swift', 'SWIFT'), ('internal_transfer', 'Internal Transfer'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='finance/supporting_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edit_requested', 'Edit Requested'), ('edited', 'Edited'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('is_correction', models.BooleanField(default=False)),
                ('edit_reason', models.TextField(blank=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='finance.financialaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('original_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_entries', to='finance.ledgertransaction')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='clients.client')),
                ('related_party_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('related_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Ledger Transaction',
                'verbose_name_plural': 'Ledger Transactions',
                'db_table': 'finance_ledger_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.financialaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.financialaccount')),
                ('credit_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_credit_entry', to='finance.ledgertransaction')),
                ('debit_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_debit_entry', to='finance.ledgertransaction')),
            ],
            options={
                'verbose_name': 'Internal Transfer',
                'verbose_name_plural': 'Internal Transfers',
                'db_table': 'finance_internal_transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_allocations', to='payments.paymentschedule')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='finance.ledgertransaction')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'db_table': 'finance_payment_allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspenseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allocated', models.BooleanField(default=False)),
                ('allocated_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('allocation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_suspense_allocations', to=settings.AUTH_USER_MODEL)),
                ('allocated_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspense_detail', to='finance.ledgertransaction')),
            ],
            options={
                'verbose_name': 'Suspense Transaction',
                'verbose_name_plural': 'Suspense Transactions',
                'db_table': 'finance_suspense_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edit_requested', 'Edit Requested')], max_length=20)),
                ('actioned_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('actioned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transaction_actions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='finance.ledgertransaction')),
            ],
            options={
                'verbose_name': 'Transaction Approval',
                'verbose_name_plural': 'Transaction Approvals',
                'db_table': 'finance_transaction_approvals',
                'ordering': ['-actioned_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('approve', 'Approve'), ('reject', 'Reject'), ('reverse', 'Reverse'), ('correct', 'Correct'), ('cancel', 'Cancel')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='finance.ledgertransaction')),
            ],
            options={
                'verbose_name': 'Transaction Audit Trail Entry',
                'verbose_name_plural': 'Transaction Audit Trail',
                'db_table': 'finance_transaction_audit_trail',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['account', 'status'], name='finance_led_account_17fe8e_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['transaction_date'], name='finance_led_transac_9afaec_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['reference_number'], name='finance_led_referen_f4a15a_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['related_party_content_type', 'related_party_object_id'], name='finance_led_related_93c5b1_idx'),
        ),
    ]
