# Generated by Django 5.1.11 on 2025-08-16 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('payments', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('contract', 'Sales Contract'), ('agreement', 'Payment Agreement'), ('logbook', 'Vehicle Logbook'), ('insurance', 'Insurance Document'), ('id_copy', 'ID Copy'), ('passport_copy', 'Passport Copy'), ('license', 'Driving License'), ('proof_income', 'Proof of Income'), ('bank_statement', 'Bank Statement'), ('receipt', 'Payment Receipt'), ('invoice', 'Invoice'), ('valuation', 'Vehicle Valuation'), ('inspection', 'Inspection Report'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal Only'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='internal', max_length=20)),
                ('password_protected', models.BooleanField(default=False)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('is_signed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.payment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
