# Generated by Django 5.1 on 2025-10-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('sales', 'Sales Person'), ('accountant', 'Accountant'), ('auctioneer', 'Auctioneer'), ('manager', 'Manager'), ('clerk', 'Clerk'), ('client', 'Client')], default='client', help_text='User role determines access permissions', max_length=20, verbose_name='User Role'),
        ),
    ]
