# Generated by Django 5.1 on 2025-10-03 07:16

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('icon', models.CharField(blank=True, help_text="Icon class (e.g., 'fa-file', 'fa-folder')", max_length=50, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for UI', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('require_expiry_date', models.BooleanField(default=False, help_text='Whether documents in this category require expiry dates')),
                ('allowed_file_types', models.CharField(blank=True, help_text="Comma-separated allowed file extensions (e.g., 'pdf,doc,docx')", max_length=200, null=True)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, help_text='Maximum file size in MB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='documents_d_name_9c92ac_idx'), models.Index(fields=['slug'], name='documents_d_slug_d17b69_idx'), models.Index(fields=['is_active'], name='documents_d_is_acti_c8e63e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description', null=True)),
                ('file', models.FileField(help_text='Document file', upload_to=apps.documents.models.document_upload_path)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='File MIME type', max_length=50, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('document_number', models.CharField(blank=True, help_text='Document reference number (e.g., contract number)', max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, help_text='Date document was issued', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date document expires', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Document version number')),
                ('is_latest_version', models.BooleanField(default=True, help_text='Whether this is the latest version')),
                ('is_private', models.BooleanField(default=False, help_text='Whether this document is private')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document is active')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times downloaded')),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Last download timestamp', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Previous version of this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Document category', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Can View'), ('download', 'Can Download'), ('edit', 'Can Edit'), ('delete', 'Can Delete'), ('manage', 'Can Manage Permissions')], help_text='Permission type', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When permission expires', null=True)),
                ('document', models.ForeignKey(help_text='Document', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document')),
                ('granted_by', models.ForeignKey(help_text='Who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_document_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User with permission', on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Permission',
                'verbose_name_plural': 'Document Permissions',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(help_text='Unique share token', max_length=64, unique=True)),
                ('password', models.CharField(blank=True, help_text='Optional password protection', max_length=128, null=True)),
                ('allow_download', models.BooleanField(default=True, help_text='Whether download is allowed')),
                ('max_downloads', models.PositiveIntegerField(blank=True, help_text='Maximum number of downloads allowed', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Current download count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When share link expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether share is active')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last access timestamp', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created share', on_delete=django.db.models.deletion.CASCADE, related_name='created_shares', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Share',
                'verbose_name_plural': 'Document Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'View Only'), ('download', 'Download'), ('edit', 'Edit'), ('delete', 'Delete')], help_text='Type of access', max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, help_text='When access occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of accessor', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device user agent', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Access notes', null=True)),
                ('document', models.ForeignKey(help_text='Document accessed', on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(help_text='User who accessed', on_delete=django.db.models.deletion.CASCADE, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['document', 'accessed_at'], name='documents_d_documen_7ee94e_idx'), models.Index(fields=['user', 'accessed_at'], name='documents_d_user_id_7f809b_idx'), models.Index(fields=['access_type'], name='documents_d_access__6aeb14_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_d_title_ccf306_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'uploaded_at'], name='documents_d_categor_193385_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='documents_d_uploade_6455fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_active', 'is_latest_version'], name='documents_d_is_acti_90fb22_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['document', 'user'], name='documents_d_documen_0435ad_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['expires_at'], name='documents_d_expires_98800a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('document', 'user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['share_token'], name='documents_d_share_t_57bd35_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['document'], name='documents_d_documen_787239_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['is_active'], name='documents_d_is_acti_0f88cd_idx'),
        ),
    ]
