# Generated by Django 5.1.11 on 2025-08-16 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='audit_logs_action__11f9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module_name', 'timestamp'], name='audit_logs_module__51d5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='audit_logs_ip_addr_919cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['is_successful'], name='audit_logs_is_succ_94f710_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['report_type', 'generated_at'], name='compliance__report__9c531e_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['start_date', 'end_date'], name='compliance__start_d_f25f47_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['generated_by'], name='compliance__generat_634a29_idx'),
        ),
        migrations.AddIndex(
            model_name='dataexport',
            index=models.Index(fields=['user', 'timestamp'], name='data_export_user_id_c10bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='dataexport',
            index=models.Index(fields=['module_name', 'timestamp'], name='data_export_module__d6cd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='dataexport',
            index=models.Index(fields=['export_type'], name='data_export_export__8e58e4_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', 'timestamp'], name='login_attem_usernam_ece61f_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'timestamp'], name='login_attem_ip_addr_340a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['is_successful'], name='login_attem_is_succ_f6e4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='system_even_event_t_beb9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['severity'], name='system_even_severit_8b827f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['resolved'], name='system_even_resolve_c35d50_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='user_sessio_last_ac_7cb421_idx'),
        ),
    ]
