# Generated by Django 5.1 on 2025-10-03 07:16

import django.core.validators
import django.db.models.deletion
import utils.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('other_names', models.CharField(blank=True, help_text='Middle name or additional names', max_length=100, verbose_name='Other Names')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('other', 'Other')], default='national_id', max_length=20, verbose_name='ID Type')),
                ('id_number', models.CharField(help_text='National ID or Passport number', max_length=50, unique=True, verbose_name='ID/Passport Number')),
                ('phone_primary', models.CharField(help_text='Format: +254712345678 or 0712345678', max_length=20, validators=[utils.validators.validate_phone_number], verbose_name='Primary Phone')),
                ('phone_secondary', models.CharField(blank=True, help_text='Alternative phone number', max_length=20, validators=[utils.validators.validate_phone_number], verbose_name='Secondary Phone')),
                ('email', models.EmailField(blank=True, help_text='Client email address', max_length=254, verbose_name='Email Address')),
                ('physical_address', models.TextField(help_text='Current residential address', verbose_name='Physical Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City/Town')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='County')),
                ('postal_address', models.CharField(blank=True, max_length=200, verbose_name='Postal Address')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Occupation')),
                ('employer', models.CharField(blank=True, max_length=200, verbose_name='Employer')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monthly income', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Income')),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, verbose_name='Next of Kin Name')),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20, validators=[utils.validators.validate_phone_number], verbose_name='Next of Kin Phone')),
                ('next_of_kin_relationship', models.CharField(blank=True, help_text='Relationship to next of kin', max_length=100, verbose_name='Relationship')),
                ('next_of_kin_address', models.TextField(blank=True, verbose_name='Next of Kin Address')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum credit allowed for this client', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Credit Limit')),
                ('current_debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total outstanding debt', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Debt')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('defaulted', 'Defaulted'), ('completed', 'Completed')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether client account is active', verbose_name='Active')),
                ('is_blacklisted', models.BooleanField(default=False, help_text='Client is blacklisted due to default or fraud', verbose_name='Blacklisted')),
                ('blacklist_reason', models.TextField(blank=True, help_text='Reason for blacklisting', verbose_name='Blacklist Reason')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the client', verbose_name='Notes')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name='Profile Photo')),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='Date Registered')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-date_registered'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('logbook', 'Logbook'), ('insurance', 'Insurance Document'), ('id_card', 'ID Card/Passport'), ('agreement', 'Agreement'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('other', 'Other')], help_text='Type of document', max_length=50, verbose_name='Document Type')),
                ('title', models.CharField(help_text='Descriptive title for the document', max_length=200, verbose_name='Document Title')),
                ('file', models.FileField(help_text='Upload document file', upload_to='clients/documents/%Y/%m/', verbose_name='File')),
                ('description', models.TextField(blank=True, help_text='Additional details about the document', verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'db_table': 'client_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(help_text='Date vehicle was purchased/assigned', verbose_name='Purchase Date')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Agreed purchase price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Purchase Price')),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Deposit Paid')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Paid')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining balance', max_digits=12, verbose_name='Balance')),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly payment amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monthly Installment')),
                ('installment_months', models.IntegerField(blank=True, help_text='Number of months for payment', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Installment Period (Months)')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual interest rate', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Interest Rate (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this purchase is active', verbose_name='Active')),
                ('is_paid_off', models.BooleanField(default=False, help_text='Whether vehicle is fully paid', verbose_name='Paid Off')),
                ('date_paid_off', models.DateField(blank=True, null=True, verbose_name='Date Paid Off')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this purchase', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_purchases', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Client Vehicle',
                'verbose_name_plural': 'Client Vehicles',
                'db_table': 'client_vehicles',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', '-date_registered'], name='clients_status_c53c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['id_number'], name='clients_id_numb_6ae1af_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_primary'], name='clients_phone_p_701eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active', 'status'], name='clients_is_acti_fcdefd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientvehicle',
            unique_together={('client', 'vehicle')},
        ),
    ]
