# Generated by Django 5.0.7 on 2026-05-09 13:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletracker',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Annual interest rate for payment plan (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Interest Rate (%)'),
        ),
    ]
