# Generated by Django 5.1 on 2026-05-10 07:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_remove_clientvehicle_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvehicle',
            name='broker_id_no',
            field=models.CharField(blank=True, help_text='Broker identification number', max_length=50, null=True, verbose_name='Broker ID Number'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='broker_name',
            field=models.CharField(blank=True, help_text='Name of the broker handling this transaction', max_length=200, null=True, verbose_name='Broker Name'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='broker_phone_no',
            field=models.CharField(blank=True, help_text='Broker contact phone number', max_length=20, null=True, verbose_name='Broker Phone Number'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission amount for the broker', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Commission Amount'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage (e.g., 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Commission Percentage'),
        ),
    ]
