# Generated by Django 5.0.7 on 2026-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_clientvehicle_broker_id_no_clientvehicle_broker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletracker',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('flexible', 'Flexible Installments'), ('deduct_from_deposit', 'Deduct from Deposit')], default='full', help_text='How the client pays for this tracker', max_length=30, verbose_name='Payment Type'),
        ),
    ]
