# Generated by Django 5.0.7 on 2026-05-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_add_payment_type_to_insurance_and_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletracker',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Tracker certificate number (if available)', max_length=100, verbose_name='Certificate Number'),
        ),
    ]
