# Generated by Django 5.0.7 on 2026-06-06

from decimal import Decimal
from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_vehicletracker_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvehicle',
            name='client_purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated client purchase price before manual adjustments', max_digits=12, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Client Purchase Price'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='extra_costs_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of extra costs with description and amount', verbose_name='Extra Costs JSON'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='extra_costs_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total extra costs deducted from final selling price', max_digits=12, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Extra Costs Total'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='final_selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Editable selling price before deducting extra costs', max_digits=12, validators=[MinValueValidator(Decimal('0.00'))], verbose_name='Final Selling Price'),
        ),
    ]
