# Generated by Django 5.0.7 on 2026-06-07 21:37

from django.db import migrations, models


def create_tracker_company_table_if_missing(apps, schema_editor):
    """Create tracker_companies table only when it does not already exist."""
    if 'tracker_companies' in schema_editor.connection.introspection.table_names():
        return
    db = schema_editor.connection.vendor
    if db == 'sqlite':
        schema_editor.execute('''
            CREATE TABLE IF NOT EXISTS "tracker_companies" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "name" varchar(200) NOT NULL UNIQUE,
                "phone" varchar(20) NULL,
                "email" varchar(254) NULL,
                "contact_person" varchar(200) NULL,
                "notes" text NULL,
                "is_active" bool NOT NULL DEFAULT 1,
                "created_at" datetime NOT NULL,
                "updated_at" datetime NOT NULL
            )
        ''')
    elif db == 'mysql':
        schema_editor.execute('''
            CREATE TABLE IF NOT EXISTS `tracker_companies` (
                `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
                `name` varchar(200) NOT NULL UNIQUE,
                `phone` varchar(20) NULL,
                `email` varchar(254) NULL,
                `contact_person` varchar(200) NULL,
                `notes` longtext NULL,
                `is_active` tinyint(1) NOT NULL DEFAULT 1,
                `created_at` datetime(6) NOT NULL,
                `updated_at` datetime(6) NOT NULL
            )
        ''')
    else:
        schema_editor.execute('''
            CREATE TABLE IF NOT EXISTS "tracker_companies" (
                "id" bigserial NOT NULL PRIMARY KEY,
                "name" varchar(200) NOT NULL UNIQUE,
                "phone" varchar(20) NULL,
                "email" varchar(254) NULL,
                "contact_person" varchar(200) NULL,
                "notes" text NULL,
                "is_active" boolean NOT NULL DEFAULT TRUE,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL
            )
        ''')


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_remove_next_of_kin_phone_validator'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TrackerCompany',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='Tracker company/vendor name', max_length=200, unique=True)),
                        ('phone', models.CharField(blank=True, help_text='Primary contact phone (optional)', max_length=20, null=True)),
                        ('email', models.EmailField(blank=True, help_text='Contact email (optional)', max_length=254, null=True)),
                        ('contact_person', models.CharField(blank=True, help_text='Contact person name (optional)', max_length=200, null=True)),
                        ('notes', models.TextField(blank=True, help_text='Additional notes (optional)', null=True)),
                        ('is_active', models.BooleanField(default=True, help_text='Whether this tracker company is active')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Tracker Company',
                        'verbose_name_plural': 'Tracker Companies',
                        'db_table': 'tracker_companies',
                        'ordering': ['name'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    create_tracker_company_table_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
