# Generated by Django 5.1 on 2026-06-07 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_agreement_signature_table_if_missing(apps, schema_editor):
    """Create agreement_signatures table only when it does not already exist."""
    if 'agreement_signatures' in schema_editor.connection.introspection.table_names():
        return
    db = schema_editor.connection.vendor
    if db == 'sqlite':
        schema_editor.execute('''
            CREATE TABLE IF NOT EXISTS "agreement_signatures" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "signer_name" varchar(200) NOT NULL,
                "signer_id_number" varchar(50) NOT NULL,
                "signature_data" text NOT NULL,
                "ip_address" char(39) NULL,
                "signed_at" datetime NOT NULL,
                "client_vehicle_id" bigint NOT NULL UNIQUE REFERENCES "client_vehicles" ("id") DEFERRABLE INITIALLY DEFERRED,
                "signed_by_id" bigint NULL REFERENCES "authentication_user" ("id") DEFERRABLE INITIALLY DEFERRED
            )
        ''')
    elif db == 'mysql':
        schema_editor.execute('''
            CREATE TABLE IF NOT EXISTS `agreement_signatures` (
                `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
                `signer_name` varchar(200) NOT NULL,
                `signer_id_number` varchar(50) NOT NULL,
                `signature_data` longtext NOT NULL,
                `ip_address` char(39) NULL,
                `signed_at` datetime(6) NOT NULL,
                `client_vehicle_id` bigint NOT NULL UNIQUE,
                `signed_by_id` bigint NULL
            )
        ''')
    else:
        schema_editor.execute('''
            CREATE TABLE IF NOT EXISTS "agreement_signatures" (
                "id" bigserial NOT NULL PRIMARY KEY,
                "signer_name" varchar(200) NOT NULL,
                "signer_id_number" varchar(50) NOT NULL,
                "signature_data" text NOT NULL,
                "ip_address" inet NULL,
                "signed_at" timestamp with time zone NOT NULL,
                "client_vehicle_id" bigint NOT NULL UNIQUE,
                "signed_by_id" bigint NULL
            )
        ''')


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_trackercompany'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AgreementSignature',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('signer_name', models.CharField(help_text='Name of the person who signed', max_length=200, verbose_name='Signer Full Name')),
                        ('signer_id_number', models.CharField(blank=True, help_text='National ID or passport used to verify identity', max_length=50, verbose_name='Signer ID / Passport')),
                        ('signature_data', models.TextField(help_text='Base-64 encoded PNG of the drawn signature', verbose_name='Signature Image Data')),
                        ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the signature was submitted', null=True, verbose_name='IP Address')),
                        ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Signed At')),
                        ('client_vehicle', models.OneToOneField(help_text='The vehicle purchase this signature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agreement_signature', to='clients.clientvehicle')),
                        ('signed_by', models.ForeignKey(blank=True, help_text='Logged-in user who submitted the signature (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_signed', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Agreement Signature',
                        'verbose_name_plural': 'Agreement Signatures',
                        'db_table': 'agreement_signatures',
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    create_agreement_signature_table_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
