# Generated by Django 5.1 on 2026-06-07 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_trackercompany'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(help_text='Name of the person who signed', max_length=200, verbose_name='Signer Full Name')),
                ('signer_id_number', models.CharField(blank=True, help_text='National ID or passport used to verify identity', max_length=50, verbose_name='Signer ID / Passport')),
                ('signature_data', models.TextField(help_text='Base-64 encoded PNG of the drawn signature', verbose_name='Signature Image Data')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the signature was submitted', null=True, verbose_name='IP Address')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Signed At')),
                ('client_vehicle', models.OneToOneField(help_text='The vehicle purchase this signature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agreement_signature', to='clients.clientvehicle')),
                ('signed_by', models.ForeignKey(blank=True, help_text='Logged-in user who submitted the signature (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agreement Signature',
                'verbose_name_plural': 'Agreement Signatures',
                'db_table': 'agreement_signatures',
            },
        ),
    ]
