# Generated by Django 5.1 on 2026-06-08 00:00

from django.db import migrations, models


def add_agreement_signature_party_fields_if_missing(apps, schema_editor):
    table_name = 'agreement_signatures'
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    fields = [
        (
            'witness_name',
            models.CharField(blank=True, help_text='Witness name if a witness signs online', max_length=200, verbose_name='Witness Full Name'),
        ),
        (
            'witness_id_number',
            models.CharField(blank=True, help_text='Witness ID or passport number', max_length=50, verbose_name='Witness ID / Passport'),
        ),
        (
            'seller_name',
            models.CharField(blank=True, help_text='Hoza representative signing the agreement', max_length=200, verbose_name='Seller Full Name'),
        ),
        (
            'witness_signature_data',
            models.TextField(blank=True, default='', help_text='Base-64 encoded PNG of the witness signature', verbose_name='Witness Signature Image Data'),
        ),
        (
            'seller_signature_data',
            models.TextField(blank=True, default='', help_text='Base-64 encoded PNG of the seller signature', verbose_name='Seller Signature Image Data'),
        ),
    ]

    AgreementSignature = apps.get_model('clients', 'AgreementSignature')
    for name, field in fields:
        if name in existing_columns:
            continue
        field.set_attributes_from_name(name)
        schema_editor.add_field(AgreementSignature, field)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_agreement_signature'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='agreementsignature',
                    name='witness_name',
                    field=models.CharField(blank=True, help_text='Witness name if a witness signs online', max_length=200, verbose_name='Witness Full Name'),
                ),
                migrations.AddField(
                    model_name='agreementsignature',
                    name='witness_id_number',
                    field=models.CharField(blank=True, help_text='Witness ID or passport number', max_length=50, verbose_name='Witness ID / Passport'),
                ),
                migrations.AddField(
                    model_name='agreementsignature',
                    name='seller_name',
                    field=models.CharField(blank=True, help_text='Hoza representative signing the agreement', max_length=200, verbose_name='Seller Full Name'),
                ),
                migrations.AddField(
                    model_name='agreementsignature',
                    name='witness_signature_data',
                    field=models.TextField(blank=True, default='', help_text='Base-64 encoded PNG of the witness signature', verbose_name='Witness Signature Image Data'),
                ),
                migrations.AddField(
                    model_name='agreementsignature',
                    name='seller_signature_data',
                    field=models.TextField(blank=True, default='', help_text='Base-64 encoded PNG of the seller signature', verbose_name='Seller Signature Image Data'),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_agreement_signature_party_fields_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]