# Generated by Django 5.1 on 2026-06-22 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_vehicletracker_payment_method_installments_json'),
        ('vehicles', '0015_broker_brokerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvehicle',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Broker linked to this sale (for ledger tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='vehicles.broker'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='broker_commission_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='Whether the broker commission for this sale has been paid', max_length=10, verbose_name='Commission Status'),
        ),
    ]
