# Generated by Django 5.1 on 2026-06-25 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0034_clientvehicle_broker_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='vehicletracker',
                    name='renewal_of',
                    field=models.ForeignKey(blank=True, help_text='The tracker record this was renewed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='clients.vehicletracker'),
                ),
            ],
        ),
    ]
