# Generated by Django 5.1 on 2026-06-26 07:33

from django.db import migrations, models


def _column_exists(connection, table_name, column_name):
    if connection.vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute(f"PRAGMA table_info({table_name})")
            return any(row[1] == column_name for row in cursor.fetchall())
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = %s AND column_name = %s
        """, [table_name, column_name])
        return cursor.fetchone() is not None


def add_column_if_not_exists(apps, schema_editor):
    connection = schema_editor.connection
    if not _column_exists(connection, 'client_vehicles', 'agreement_paybill'):
        with connection.cursor() as cursor:
            cursor.execute(
                "ALTER TABLE client_vehicles ADD COLUMN agreement_paybill varchar(20) NOT NULL DEFAULT ''"
            )


def remove_column_if_exists(apps, schema_editor):
    connection = schema_editor.connection
    if _column_exists(connection, 'client_vehicles', 'agreement_paybill'):
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE client_vehicles DROP COLUMN agreement_paybill")


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_agreementversion'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='clientvehicle',
                    name='agreement_paybill',
                    field=models.CharField(blank=True, default='', help_text='Paybill number to print on the sales agreement', max_length=20, verbose_name='Agreement Paybill'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_column_if_not_exists, remove_column_if_exists),
            ],
        ),
    ]
