# Generated by Django 5.1 on 2026-06-26 07:33

from django.db import migrations, models


def add_column_if_not_exists(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'client_vehicles' AND column_name = 'agreement_paybill'
        """)
        if cursor.fetchone() is None:
            cursor.execute(
                "ALTER TABLE client_vehicles ADD COLUMN agreement_paybill varchar(20) NOT NULL DEFAULT ''"
            )


def remove_column_if_exists(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'client_vehicles' AND column_name = 'agreement_paybill'
        """)
        if cursor.fetchone() is not None:
            cursor.execute("ALTER TABLE client_vehicles DROP COLUMN agreement_paybill")


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_agreementversion'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='clientvehicle',
                    name='agreement_paybill',
                    field=models.CharField(blank=True, default='', help_text='Paybill number to print on the sales agreement', max_length=20, verbose_name='Agreement Paybill'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_column_if_not_exists, remove_column_if_exists),
            ],
        ),
    ]
