# Generated by Django 5.1 on 2026-06-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_agreementversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvehicle',
            name='agreement_paybill',
            field=models.CharField(blank=True, default='', help_text='Paybill number to print on the sales agreement', max_length=20, verbose_name='Agreement Paybill'),
        ),
    ]
