# Generated by Django 5.1 on 2026-06-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_clientvehicle_agreement_paybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('defaulted', 'Defaulted'), ('completed', 'Completed'), ('repossessed', 'Repossessed')], db_index=True, default='active', max_length=20, verbose_name='Status'),
        ),
    ]
