# Generated by Django 5.1 on 2026-07-17 16:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_alter_client_status'),
        ('payments', '0018_alter_accounttransaction_direction'),
        ('vehicles', '0022_vehicle_allow_photo_downloads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Auto-generated: PF-YYYYMMDD-XXXX', max_length=30, unique=True, verbose_name='Proforma Number')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Issue')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('awaiting_commitment', 'Awaiting Commitment'), ('deposit_paid', 'Deposit Paid'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('converted', 'Converted to Sale')], db_index=True, default='draft', max_length=25)),
                ('payment_mode', models.CharField(choices=[('bank_financing', 'Bank Financing'), ('cash', 'Cash / Own Funds'), ('installment', 'Hire Purchase')], default='bank_financing', max_length=20, verbose_name='Payment Mode')),
                ('financing_bank', models.CharField(blank=True, help_text='Financier when payment mode is bank financing', max_length=200, verbose_name='Bank / Financial Institution')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Vehicle Selling Price')),
                ('deposit_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Deposit Required')),
                ('financing_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount expected from the bank/financier', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Financing Amount')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Purchase Price')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Payment Terms')),
                ('bank_details', models.TextField(blank=True, verbose_name='Company Bank Details')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='Terms & Conditions')),
                ('notes', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_approved', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_cancelled', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='clients.client')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_converted', to=settings.AUTH_USER_MODEL)),
                ('converted_client_vehicle', models.OneToOneField(blank=True, help_text='The sale record this proforma was converted into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proforma', to='clients.clientvehicle')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_prepared', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Proforma Invoice',
                'verbose_name_plural': 'Proforma Invoices',
                'db_table': 'proforma_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('equity_hoza', 'Equity Hoza'), ('dib_hoza', 'DIB Hoza'), ('coop_hoza', 'COOP Hoza'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, help_text='Account where the deposit money landed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_deposits', to='payments.account')),
                ('account_transaction', models.ForeignKey(blank=True, help_text='Ledger entry posted when this deposit was confirmed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_deposits', to='payments.accounttransaction')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_deposits_confirmed', to=settings.AUTH_USER_MODEL)),
                ('converted_payment', models.ForeignKey(blank=True, help_text='Payment created when the proforma converted to a sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_deposits', to='payments.payment')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_deposits_reversed', to=settings.AUTH_USER_MODEL)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='clients.proformainvoice')),
            ],
            options={
                'verbose_name': 'Proforma Deposit',
                'verbose_name_plural': 'Proforma Deposits',
                'db_table': 'proforma_deposits',
                'ordering': ['-payment_date', '-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_period_days', models.PositiveIntegerField(default=7, help_text='Days a deposit-backed reservation holds a vehicle by default', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Default Reservation Period (days)')),
                ('notify_days_before', models.PositiveIntegerField(default=1, help_text='Days before expiry to notify the salesperson and managers', verbose_name='Notify Before Expiry (days)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation Setting',
                'verbose_name_plural': 'Reservation Settings',
                'db_table': 'reservation_settings',
            },
        ),
        migrations.CreateModel(
            name='VehicleReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired — Pending Review'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('converted', 'Converted to Sale')], db_index=True, default='active', max_length=15)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_days', models.PositiveIntegerField(default=7)),
                ('expiry_date', models.DateField()),
                ('extension_count', models.PositiveIntegerField(default=0)),
                ('extended_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True)),
                ('expiry_notified', models.BooleanField(default=False, help_text='Pre-expiry warning already sent to salesperson/manager')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_reservations', to='clients.client')),
                ('confirmed_by', models.ForeignKey(help_text='Staff member who confirmed the deposit/reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_confirmed', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(blank=True, help_text='The deposit that triggered this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='clients.proformadeposit')),
                ('extended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_extended', to=settings.AUTH_USER_MODEL)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clients.proformainvoice')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_released', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Reservation',
                'verbose_name_plural': 'Vehicle Reservations',
                'db_table': 'vehicle_reservations',
                'ordering': ['-reserved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['status', '-created_at'], name='proforma_in_status_9c14bf_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['vehicle', 'status'], name='proforma_in_vehicle_f2d934_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['client', 'status'], name='proforma_in_client__196151_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclereservation',
            index=models.Index(fields=['status', 'expiry_date'], name='vehicle_res_status_cac306_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclereservation',
            index=models.Index(fields=['vehicle', 'status'], name='vehicle_res_vehicle_e20cf3_idx'),
        ),
    ]
