# Generated by Django 5.1 on 2026-07-19 06:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_proformainvoice_proformadeposit_reservationsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvehicle',
            name='deposit_deductions_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON breakdown of amounts deducted from the deposit (insurance/tracker line items)', verbose_name='Deposit Deductions JSON'),
        ),
        migrations.AddField(
            model_name='clientvehicle',
            name='deposit_deductions_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deducted from the deposit for insurance/tracker items paid via "Deduct from Deposit"', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Deposit Deductions Total'),
        ),
        migrations.AddField(
            model_name='vehicletracker',
            name='deposit_payment_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Deposit Payment Location'),
        ),
        migrations.AddField(
            model_name='vehicletracker',
            name='deposit_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('equity_hoza', 'Equity Hoza'), ('dib_hoza', 'DIB Hoza'), ('coop_hoza', 'COOP Hoza'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('other', 'Other')], default='cash', max_length=30, verbose_name='Deposit Payment Method'),
        ),
        migrations.AddField(
            model_name='vehicletracker',
            name='deposit_splits_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of {method, amount, reference, location} when the deposit was split across methods', verbose_name='Deposit Split Payments (JSON)'),
        ),
        migrations.AddField(
            model_name='vehicletracker',
            name='deposit_transaction_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Deposit Transaction Reference'),
        ),
        migrations.AlterField(
            model_name='vehicletracker',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('equity_hoza', 'Equity Hoza'), ('dib_hoza', 'DIB Hoza'), ('coop_hoza', 'COOP Hoza'), ('kcb_ke', 'KCB KE'), ('absa_ke', 'ABSA KE'), ('equity_ke', 'EQUITY KE'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('other', 'Other')], default='cash', help_text='Method used to pay for this tracker', max_length=30, verbose_name='Payment Method'),
        ),
    ]
