# Generated by Django 5.1 on 2026-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_clientvehicle_deposit_deductions_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='company_account',
            field=models.CharField(blank=True, choices=[('equity', 'Equity Bank — Moi Avenue Branch, Mombasa'), ('dib', 'DIB (Dubai Islamic Bank) — Kilindini Branch, Mombasa'), ('coop', 'Co-operative Bank of Kenya — Nkrumah Road Branch, Mombasa')], help_text='Which company bank account to print on the invoice', max_length=10, verbose_name='Company Account'),
        ),
    ]
