# Generated by Django 5.1 on 2026-07-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_proformainvoice_company_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoice',
            name='payment_terms',
        ),
    ]
