# Generated by Django 5.1 on 2026-08-30 14:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0042_remove_proformainvoice_payment_terms'),
        ('expenses', '0003_expense_transaction_type'),
        ('vehicles', '0022_vehicle_allow_photo_downloads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvehicle',
            name='vehicle_price_before_sale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of Vehicle.selling_price immediately before this sale overwrote it. Set once at assignment time; used to restore the vehicle price if returned. Null for sales made before this field existed — Return Vehicle falls back to Vehicle.purchase_price in that case.', max_digits=12, null=True, verbose_name='Vehicle Price Before Sale'),
        ),
        migrations.CreateModel(
            name='ClientVehicleSecondaryBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Commission Amount')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Commission Percentage')),
                ('commission_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='Independent of the primary broker commission_status on this sale.', max_length=10, verbose_name='Commission Status')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_sales', to='vehicles.broker')),
                ('client_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_brokers', to='clients.clientvehicle')),
            ],
            options={
                'verbose_name': 'Secondary Broker',
                'verbose_name_plural': 'Secondary Brokers',
                'db_table': 'client_vehicle_secondary_brokers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(default=django.utils.timezone.now, verbose_name='Return Date')),
                ('restored_price', models.DecimalField(decimal_places=2, help_text='Price the vehicle was restored to (pre-sale selling_price, or purchase_price fallback).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Restored Vehicle Price')),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Snapshot of the client's total_paid at the moment of return.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount Refunded / Written Off')),
                ('reason', models.TextField(blank=True, verbose_name='Reason / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_vehicle', models.OneToOneField(help_text='The sale record this return reverses.', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_return', to='clients.clientvehicle')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_returns_processed', to=settings.AUTH_USER_MODEL)),
                ('refund_expense', models.ForeignKey(blank=True, help_text='Auto-created CREDIT expense that writes off amount_refunded (null if amount was 0).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_returns', to='expenses.expense')),
            ],
            options={
                'verbose_name': 'Vehicle Return',
                'verbose_name_plural': 'Vehicle Returns',
                'db_table': 'client_vehicle_returns',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
    ]
